import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import {
    familyMatches,
    familyWord,
    formatRelatedLine,
    jaccard,
    lookupKey,
    npmi,
    parseRelatedLine,
    trimTop,
} from '../scripts/shared/tagRelated.js';

const projectRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = relativePath => fs.readFileSync(path.join(projectRoot, relativePath), 'utf8');

test('lookupKey maps prompt spellings to dictionary keys', () => {
    assert.equal(lookupKey('Long Hair'), 'long_hair');
    assert.equal(lookupKey('(long hair:1.20)'), 'long_hair');
    assert.equal(lookupKey('~blue  eyes'), 'blue_eyes');
    assert.equal(lookupKey(''), '');
});

test('familyWord is the last underscore part', () => {
    assert.equal(familyWord('long_hair'), 'hair');
    assert.equal(familyWord('very long hair'), 'hair');
    assert.equal(familyWord('smile'), 'smile');
    assert.equal(familyWord(''), '');
});

test('npmi rewards specific pairs over mega tags', () => {
    const total = 1_000_000;
    // "very_long_hair" (20k posts) appears almost only with long_hair (300k)
    const specific = npmi(300_000, 20_000, 19_000, total);
    // "1girl" (600k) co-occurs with long_hair a lot, but only in proportion to its size
    const generic = npmi(300_000, 600_000, 200_000, total);
    assert.ok(specific > generic, `${specific} > ${generic}`);
    assert.ok(specific > 0 && specific <= 1);
    assert.equal(npmi(10, 10, 0, total), 0);
    assert.equal(npmi(0, 10, 5, total), 0);
    assert.ok(Math.abs(npmi(100, 100, 10, total) - npmi(100, 100, 10, total)) < 1e-12);
});

test('jaccard and the line format round-trip', () => {
    assert.equal(jaccard(100, 50, 25), 25 / 125);
    assert.equal(jaccard(0, 0, 0), 0);
    const line = formatRelatedLine('long_hair', [{ tag: 'very_long_hair', score: 212.4 }, { tag: 'blue_hair', score: 90 }]);
    assert.equal(line, 'long_hair\tvery_long_hair:212 blue_hair:90');
    assert.deepEqual(parseRelatedLine(line), { tag: 'long_hair', related: [{ tag: 'very_long_hair', score: 212 }, { tag: 'blue_hair', score: 90 }] });
    assert.equal(parseRelatedLine('no tab here'), null);
    assert.deepEqual(parseRelatedLine('x\t'), { tag: 'x', related: [] });
});

test('familyMatches finds whole-word matches from the autocomplete list, most used first', () => {
    const candidates = [
        { prompt: 'hair_ornament', group: 0, heat: 900 },
        { prompt: 'long_hair', group: 0, heat: 5000 },
        { prompt: 'hairband', group: 0, heat: 800 },   // substring only
        { prompt: 'blue_hair', group: 4, heat: 700 },  // wrong group
        { prompt: 'hair', group: 0, heat: 10 },
    ];
    const matches = familyMatches('hair', candidates, { limit: 5, exclude: new Set(['hair']), allowGroups: new Set([0]) });
    assert.deepEqual(matches.map(m => m.tag), ['long_hair', 'hair_ornament']);
    assert.deepEqual(familyMatches('', candidates), []);
});

test('trimTop keeps the strongest entries', () => {
    const entries = [{ tag: 'a', score: 1 }, { tag: 'b', score: 9 }, { tag: 'c', score: 5 }];
    assert.deepEqual(trimTop(entries, 2).map(e => e.tag), ['b', 'c']);
});

test('the shipped dictionary parses and carries hair modifiers for long_hair', () => {
    const dictionary = path.join(projectRoot, 'data', 'tag_related.txt');
    assert.ok(fs.existsSync(dictionary), 'data/tag_related.txt is generated by scripts/buildTagRelated.mjs');
    const text = fs.readFileSync(dictionary, 'utf8');
    const line = text.split('\n').find(candidate => candidate.startsWith('long_hair\t'));
    assert.ok(line, 'long_hair has an entry');
    const parsed = parseRelatedLine(line);
    assert.ok(parsed.related.length >= 5);
    assert.ok(parsed.related.some(entry => entry.tag.endsWith('_hair')), 'a hair modifier shows up among the neighbours');
    for (let i = 1; i < parsed.related.length; i++) assert.ok(parsed.related[i - 1].score >= parsed.related[i].score, 'sorted by score');
});

test('renderer, preload, web socket API and main process are wired for related tags', () => {
    assert.match(read('scripts/preload.js'), /tagRelated: async \(tag, options\) => ipcRenderer\.invoke\('tag-related', tag, options\)/);
    assert.match(read('scripts/webserver/back/wsService.js'), /'tagRelated': \(params = \[\]\)=> getRelatedTags\(\.\.\.params\)/);
    assert.match(read('main.js'), /setupTagRelatedBackend\(\)/);
    assert.match(read('scripts/renderer.js'), /fetchRelated: value => fetchRelatedTags\(value\)/);
    const field = read('scripts/renderer/components/tagCapsuleField.js');
    assert.match(field, /tag-capsule-suggest-chip/);
    assert.match(field, /scheduleSuggestions\(index\)/, 'the strip follows chip focus');
    assert.match(field, /showRelated: id =>/);
    assert.match(field, /localStorage\.getItem\(SUGGEST_STORAGE_KEY\)/, 'toggle is remembered');
    const language = JSON.parse(read('data/language.json'));
    for (const key of ['tag_ui_related_title', 'tag_ui_related_cooccur', 'tag_ui_related_family', 'tag_ui_related_none', 'tag_ui_related_toggle']) {
        assert.equal(typeof language['en-US'][key], 'string', `${key} en`);
        assert.equal(typeof language['zh-CN'][key], 'string', `${key} zh`);
    }
    assert.match(read('data/THIRD_PARTY_NOTICES.md'), /SpadeA\/danbooru-tag-csv/);
});
