import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(scriptDir, '..', 'data');
const characterPath = path.join(dataDir, 'character_names.json');
const sourcePath = path.join(dataDir, 'waiIllustriousSDXL_v160_characters.csv');
const officialWorkPath = path.join(dataDir, 'official_work_names.json');

const normalize = value => String(value ?? '')
  .trim()
  .toLowerCase()
  .replace(/\s+/g, ' ');

// Japanese UI uses the Japanese market name when an established one exists.
// If no Japanese title is established, the original official title remains.
const WORK_NAMES = {
  fate: 'Fate',
  'fate/extra': 'Fate/EXTRA',
  'fate/prototype': 'Fate/Prototype',
  'fate/zero': 'Fate/Zero',
  'fate/extra ccc': 'Fate/EXTRA CCC',
  'fate/grand order': 'Fate/Grand Order',
  kancolle: '艦隊これくしょん -艦これ-',
  'azur lane': 'アズールレーン',
  'blue archive': 'ブルーアーカイブ',
  pokemon: 'ポケモン',
  'pokemon go': 'Pokémon GO',
  arknights: 'アークナイツ',
  "girls' frontline": 'ドールズフロントライン',
  umamusume: 'ウマ娘 プリティーダービー',
  'fire emblem': 'ファイアーエムブレム',
  'granblue fantasy': 'グランブルーファンタジー',
  'genshin impact': '原神',
  'kemono friends': 'けものフレンズ',
  'league of legends': 'リーグ・オブ・レジェンド',
  'princess connect!': 'プリンセスコネクト！Re:Dive',
  'girls und panzer': 'ガールズ＆パンツァー',
  'senran kagura': '閃乱カグラ',
  touhou: '東方Project',
  naruto: 'NARUTO -ナルト-',
  overwatch: 'オーバーウォッチ',
  'chainsaw man': 'チェンソーマン',
  'one piece': 'ONE PIECE',
  konosuba: 'この素晴らしい世界に祝福を！',
  splatoon: 'スプラトゥーン',
  xenoblade: 'ゼノブレイド',
  'honkai impact': '崩壊3rd',
  'honkai star rail': '崩壊：スターレイル',
  'final fantasy': 'ファイナルファンタジー',
  persona: 'ペルソナ',
  idolmaster: 'アイドルマスター',
  'animal crossing': 'どうぶつの森',
  mario: 'マリオ',
  'yu-gi-oh!': '遊☆戯☆王',
  'jujutsu kaisen': '呪術廻戦',
  'street fighter': 'ストリートファイター',
  'dragon ball': 'ドラゴンボール',
  'devil may cry': 'デビル メイ クライ',
  'princess principal': 'プリンセス・プリンシパル',
  'sailor moon': '美少女戦士セーラームーン',
  tekken: '鉄拳',
  'boku no hero academia': '僕のヒーローアカデミア',
  'shingeki no kyojin': '進撃の巨人',
  'mega man': 'ロックマン',
  'mega man zx': 'ロックマン ゼクス',
  'dungeon meshi': 'ダンジョン飯',
  nikke: '勝利の女神：NIKKE',
  'spy x family': 'SPY×FAMILY',
  undertale: 'UNDERTALE',
  nekopara: 'NEKOPARA',
  'monster hunter': 'モンスターハンター',
  'project sekai': 'プロジェクトセカイ カラフルステージ！ feat. 初音ミク',
  'persona 4': 'ペルソナ4',
  'persona 5': 'ペルソナ5',
  nier: 'NieR',
  'ranma 1/2': 'らんま1/2',
  'zombie land saga': 'ゾンビランドサガ',
  'final fight': 'ファイナルファイト',
  'kimetsu no yaiba': '鬼滅の刃',
  bleach: 'BLEACH',
  hetalia: 'ヘタリア',
  neptunia: '超次元ゲイム ネプテューヌ',
  omori: 'OMORI',
  'zenless zone zero': 'ゼンレスゾーンゼロ',
  'taimanin asagi': '対魔忍アサギ',
  pgr: 'パニシング：グレイレイヴン',
  'ben 10': 'ベン10',
  'ff7': 'ファイナルファンタジーVII',
  'ff8': 'ファイナルファンタジーVIII',
  'ff10': 'ファイナルファンタジーX',
  'ff12': 'ファイナルファンタジーXII',
  'final fantasy xii': 'ファイナルファンタジーXII',
  dq3: 'ドラゴンクエストIII そして伝説へ…',
  'touken ranbu': '刀剣乱舞',
  'aoki hagane no arpeggio': '蒼き鋼のアルペジオ',
  'the lion king': 'ライオン・キング',
  'golden kamuy': 'ゴールデンカムイ',
  'donkey kong': 'ドンキーコング',
  overlord: 'オーバーロード',
  'howl no ugoku shiro': 'ハウルの動く城',
  'jojo no kimyou na bouken': 'ジョジョの奇妙な冒険',
  'cardcaptor sakura': 'カードキャプターさくら',
  'kino no tabi': 'キノの旅',
  'majo no takkyuubin': '魔女の宅急便',
  gintama: '銀魂',
  'steins gate': 'STEINS;GATE',
  'mushoku tensei': '無職転生 ～異世界行ったら本気だす～',
  'lycoris recoil': 'リコリス・リコイル',
  beastars: 'BEASTARS',
  'high school dxd': 'ハイスクールD×D',
  'mahou shoujo ni akogarete': '魔法少女にあこがれて',
  'under night in-birth': 'UNDER NIGHT IN-BIRTH',
  'punch out': 'パンチアウト!!',
  'kusuriya no hitorigoto': '薬屋のひとりごと',
  maoyuu: 'まおゆう魔王勇者',
  'silent hill': 'SILENT HILL',
  tmnt: 'ティーンエイジ・ミュータント・ニンジャ・タートルズ',
  'my little pony': 'マイリトルポニー',
  'hataraku saibou': 'はたらく細胞',
  'touhou bougetsushou': '東方儚月抄',
  'eiyuu densetsu': '英雄伝説',
  metroid: 'メトロイド',
  'slam dunk': 'SLAM DUNK',
  'saya no uta': '沙耶の唄',
  'madoka magica': '魔法少女まどか☆マギカ',
  'shoujo shuumatsu ryokou': '少女終末旅行',
  inuyasha: '犬夜叉',
  'reverse 1999': 'リバース：1999',
  nanoha: '魔法少女リリカルなのは',
  'gundam build divers re rise': 'ガンダムビルドダイバーズRe:RISE',
  vocaloid: 'VOCALOID',
  'tokyo mew mew': '東京ミュウミュウ',
  'tales of the abyss': 'テイルズ オブ ジ アビス',
  sekaiju: '世界樹の迷宮',
  'puniru wa kawaii slime': 'ぷにるはかわいいスライム',
  'metaphor refantazio': 'メタファー：リファンタジオ',
  housamo: '東京放課後サモナーズ',
  'rain code': '超探偵事件簿 レインコード',
  'gakkou gurashi!': 'がっこうぐらし！',
  'gegege no kitarou': 'ゲゲゲの鬼太郎',
  shuffle: 'SHUFFLE!',
  zootopia: 'ズートピア',
  'little busters': 'リトルバスターズ！',
  transformers: 'トランスフォーマー',
  'komi-san wa komyushou desu': '古見さんは、コミュ症です。',
  'deltarune': 'DELTARUNE',
  utawarerumono: 'うたわれるもの',
  'god of war': 'ゴッド・オブ・ウォー',
  blazblue: 'BLAZBLUE',
  'fire emblem fates': 'ファイアーエムブレムif',
  'type-moon': 'TYPE-MOON',
  'dark souls': 'DARK SOULS',
  'sinoalice': 'SINoALICE',
  'nige jouzu no wakagimi': '逃げ上手の若君',
  'how to train your dragon': 'ヒックとドラゴン',
  'arknights endfield': 'アークナイツ：エンドフィールド',
  'vocaloid4': 'VOCALOID4',
  'stellar blade': 'ステラーブレイド',
  'ff14': 'ファイナルファンタジーXIV',
  'dq4': 'ドラゴンクエストIV 導かれし者たち',
  dq11: 'ドラゴンクエストXI 過ぎ去りし時を求めて',
  'mother 3': 'MOTHER3',
  'oshi no ko': '【推しの子】',
  'girls band cry': 'ガールズバンドクライ',
  'rozen maiden': 'ローゼンメイデン',
  'heaven burns red': 'ヘブンバーンズレッド',
  'friday the 13th': '13日の金曜日',
  jojo: 'ジョジョの奇妙な冒険',
  'saru getchu': 'サルゲッチュ',
  precure: 'プリキュア',
  'x-men': 'X-MEN',
  'va-11 hall-a': 'VA-11 Hall-A',
  'angel beats!': 'Angel Beats!',
  'pc-98': 'PC-98',
  vtuber: 'VTuber',
  skullgirls: 'Skullgirls',
  'five nights at freddy\'s': "Five Nights at Freddy's",
  'project moon': 'Project Moon',
  'american mcgee\'s alice': "American McGee's Alice",
  'la+ darknesss': 'ラプラス・ダークネス',
  'houshou marine': '宝鐘マリン',
  'hakos baelz': 'ハコス・ベールズ',
  'nanashi mumei': '七詩ムメイ',
  'inugami korone': '戌神ころね',
  'shishiro botan': '獅白ぼたん',
  'momosuzu nene': '桃鈴ねね',
  'shiranui flare': '不知火フレア',
  'takanashi kiara': '小鳥遊キアラ',
  'ninomae ina\'nis': '一伊那尓栖',
  'sakamata chloe': '沙花叉クロヱ',
  'mori calliope': '森カリオペ',
  'sora no otoshimono': 'そらのおとしもの',
  chobits: 'ちょびっツ',
  'odin sphere': 'オーディンスフィア',
  'world of warcraft': 'World of Warcraft',
  planetarian: 'planetarian ～ちいさなほしのゆめ～',
  marvel: 'マーベル',
  hololive: 'ホロライブ',
  'ragnarok online': 'ラグナロクオンライン',
  'kingdom hearts': 'キングダム ハーツ',
  tales: 'テイルズ オブ',
  umineko: 'うみねこのなく頃に',
  'alice in wonderland': '不思議の国のアリス',
  "dragon's crown": 'ドラゴンズクラウン',
  'black lagoon': 'BLACK LAGOON',
  tsukihime: '月姫',
  'monster musume': 'モンスター娘のいる日常',
  'made in abyss': 'メイドインアビス',
  nijisanji: 'にじさんじ',
  'doki doki literature club': 'ドキドキ文芸部！',
  "queen's blade": 'クイーンズブレイド',
  'one-punch man': 'ワンパンマン',
  berserk: 'ベルセルク',
  'darker than black': 'DARKER THAN BLACK -黒の契約者-',
  'goblin slayer!': 'ゴブリンスレイヤー！',
  'darling in the franxx': 'ダーリン・イン・ザ・フランキス',
  'no game no life': 'ノーゲーム・ノーライフ',
  cyberpunk: 'サイバーパンク2077',
  'tears of themis': '未定事件簿',
  sao: 'ソードアート・オンライン',
  'sao-alo': 'ソードアート・オンライン：アリシゼーション・リコリス',
  psg: 'パンティ＆ストッキングwithガーターベルト',
  dq5: 'ドラゴンクエストV 天空の花嫁',
  'p&d': 'パズル＆ドラゴンズ',
  doa: 'デッド オア アライブ',
  puyopuyo: 'ぷよぷよ',
  'tenki no ko': '天気の子',
  'needy girl overdose': 'NEEDY GIRL OVERDOSE',
  'eureka seven': '交響詩篇エウレカセブン',
  'soul eater': 'ソウルイーター',
  'sengoku basara': '戦国BASARA',
  maidragon: '小林さんちのメイドラゴン',
  elsword: 'エルソード',
  'dungeon and fighter': 'アラド戦記',
  'princess tutu': 'プリンセスチュチュ',
  warioware: 'メイド イン ワリオ',
  'summon night': 'サモンナイト',
  disgaea: '魔界戦記ディスガイア',
  grandia: 'グランディア',
  'shadows house': 'シャドーハウス',
  'plastic memories': 'プラスティック・メモリーズ',
  danganronpa: 'ダンガンロンパ',
  'chrono trigger': 'クロノ・トリガー',
  'metal gear': 'メタルギア',
  'dragon quest': 'ドラゴンクエスト',
  'kill me baby': 'キルミーベイベー',
  'school rumble': 'スクールランブル',
  symphogear: '戦姫絶唱シンフォギア',
  sonic: 'ソニック・ザ・ヘッジホッグ',
  'd-frag!': 'ディーふらぐ！',
  'love live!': 'ラブライブ！',
  'black rock shooter': 'ブラック★ロックシューター',
  'nier automata': 'NieR:Automata',
  'oshiro project': '御城プロジェクト:RE',
  'toaru majutsu no index': 'とある魔術の禁書目録',
  demonbane: '斬魔大聖デモンベイン',
  digimon: 'デジモン',
  'sousou no frieren': '葬送のフリーレン',
  'star wars': 'スター・ウォーズ',
  'metal gear solid': 'メタルギアソリッド',
  ppg: 'パワーパフガールズ',
  ttgl: '天元突破グレンラガン',
  'houseki no kuni': '宝石の国',
  'nyaruko-san': '這いよれ！ニャル子さん',
  'fresh precure!': 'フレッシュプリキュア！',
  'tate no yuusha no nariagari': '盾の勇者の成り上がり',
  ookami: '大神',
  'tales of abyss': 'テイルズ オブ ジ アビス',
  'the ancient magus\' bride': '魔法使いの嫁',
  'tera online': 'TERA',
  're zero': 'Re:ゼロから始める異世界生活',
  'fullmetal alchemist': '鋼の錬金術師',
  'puss in boots': '長ぐつをはいたネコ',
  'path to nowhere': '無期迷途',
  'resident evil': 'バイオハザード',
  'spider-man': 'スパイダーマン',
  'wuthering waves': '鳴潮',
  'star fox': 'スターフォックス',
  pso2: 'ファンタシースターオンライン2',
  mushishi: '蟲師',
  'shingeki no bahamut': '神撃のバハムート',
  'fate/samurai remnant': 'Fate/Samurai Remnant',
};

const GLOBAL_NAMES = {
  '2b': '2B',
  '9s': '9S',
  a2: 'A2',
  '2k-tan': '2Kたん',
  'adepta sororitas': 'アデプタ・ソロリタス',
  'abe nana': '安部菜々',
  'ada wong': 'エイダ・ウォン',
  'adrien agreste': 'アドリアン・アグレスト',
  'aerith gainsborough': 'エアリス・ゲインズブール',
  'afuro terumi': 'アフロディ',
  'agatsuma zenitsu': '我妻善逸',
  'agnes claudel': 'アグネス・クローデル',
  'agrias oaks': 'アグリアス・オークス',
  'aihara mei': '藍原芽衣',
  'aihara yuzu': '藍原柚子',
  'aijou karen': '愛城華恋',
  'aika granzchesta': '藍華・S・グランチェスタ',
  'aile (mega man zx)': 'エール',
  'byleth (fire emblem)': 'ベレト/ベレス',
  'byleth (female) (fire emblem)': 'ベレス（女性）',
  'byleth (female) (summer) (fire emblem)': 'ベレス（女性）（夏衣装）',
  'byleth (male) (fire emblem)': 'ベレト（男性）',
  'akemi homura': '暁美ほむら',
  'akiyama mio': '秋山澪',
  'akiyama mizuki': '秋山瑞希',
  'akizuki ritsuko': '秋月律子',
  'akuma homura': '悪魔ほむら',
  'alatreon (monster hunter)': 'アルバトリオン',
  'alcina dimitrescu': 'アルシナ・ディミトレスク',
  'amami rantaro': '天海蘭太郎',
  'amamiya ren': '雨宮蓮',
  'amane kanata': '天音かなた',
  'amaterasu (ookami)': 'アマテラス',
  'android 18': '人造人間18号',
  'ange katrina': 'アンジュ・カトリーナ',
  'annie leonhart': 'アニ・レオンハート',
  'anise tatlin (tales of abyss)': 'アニス・タトリン',
  'anisphia wynn palettia': 'アニスフィア・ウィン・パレッティア',
  'anjou naruko': '安城鳴子',
  'aoba kokona': '青羽ここな',
  'aoba moca': '青葉モカ',
  'aoyama sumika': '青山スミカ',
  'aozaki aoko': '蒼崎青子',
  'apricot the lich': 'アプリコット・ザ・リッチ',
  'aragaki shinjirou': '荒垣真次郎',
  'arataki itto': '荒瀧一斗',
  'arcueid brunestud': 'アルクェイド・ブリュンスタッド',
  'armin arlert': 'アルミン・アルレルト',
  'asagami fujino': '浅上藤乃',
  'asakura ryouko': '朝倉涼子',
  'asakura toru': '朝倉透',
  'asami sato': '佐藤麻美',
  'ashelia b\'nargin dalmasca': 'アーシェ・バナルガン・ダルマスカ',
  'asui tsuyu': '蛙吹梅雨',
  'athena cykes': '綾里真宵',
  'ayase eli': '絢瀬絵里',
  'ayase honoka': '高坂穂乃果',
  'ayunda risu': 'アユンダ・リス',
  'azusa nakano': '中野梓',
  'balthier (final fantasy xii)': 'バルフレア',
  'barret wallace (ff7)': 'バレット・ウォーレス',
  'beatrice (re zero)': 'ベアトリス',
  'beelzebub (helltaker)': 'ベルゼブブ',
  'bruno bucciarati': 'ブローノ・ブチャラティ',
  'busujima saeko': '毒島冴子',
  'c.c.': 'C.C.',
  'cagalli yula athha': 'カガリ・ユラ・アスハ',
  'caren hortensia': 'カレン・オルテンシア',
  'chun-li': '春麗',
  'cinnabar (houseki no kuni)': 'シンシャ',
  'clownpiece': 'クラウンピース',
  'cure blossom': 'キュアブロッサム',
  'cure marine': 'キュアマリン',
  'cure sky': 'キュアスカイ',
  'deidara (naruto)': 'デイダラ',
  'dekomori sanae': '凸守早苗',
  'dimitri alexandre blaiddyd': 'ディミトリ＝アレクサンドル＝ブレーダッド',
  'dizzy (guilty gear)': 'ディズィー',
  'dokugamine riruka (bleach)': '毒ヶ峰リルカ',
  'doujima nanako': '堂島菜々子',
  'douki-chan (douki-chan)': '同期ちゃん',
  'eila ilmatar juutilainen': 'エイラ・イルマタル・ユーティライネン',
  'elaina (majo no tabitabi)': 'イレイナ',
  'elizabeth rose bloodflame': 'エリザベス・ローズ・ブラッドフレイム',
  'emilia (re zero)': 'エミリア',
  'emiya kiritsugu': '衛宮切嗣',
  'emiya shirou': '衛宮士郎',
  'endeavor (boku no hero academia)': 'エンデヴァー',
  'erika (blue archive)': 'エリカ',
  'eruruu': 'エルルゥ',
  'esdeath': 'エスデス',
  'euphemia li britannia': 'ユーフェミア・リ・ブリタニア',
  'falin touden': 'ファリン・トーデン',
  'fate testarossa': 'フェイト・テスタロッサ',
  'fi (zelda)': 'ファイ',
  'filo (tate no yuusha no nariagari)': 'フィーロ',
  'fire keeper': '火防女',
  'firion': 'フリオニール',
  'fujibayashi kyou': '藤林杏',
  'fujibayashi ryou': '藤林椋',
  'fujimaru ritsuka': '藤丸立香',
  'fujino shizuru': '藤乃静留',
  'fujishima megumi': '藤島慈',
  'fujita kotone': '藤田ことね',
  'fujiwara hajime': '藤原肇',
  'fujiwara no mokou': '藤原妹紅',
  'fukawa toko': '腐川冬子',
  'fukuda noriko': '福田典子',
  'fukuji mihoko': '福路美穂子',
  'funami yui': '船見結衣',
  'furukawa nagisa': '古河渚',
  'fushiguro megumi': '伏黒恵',
  'futaba anzu': '双葉杏',
  'futaba sana': '双葉サナ',
  'futami ami': '双海亜美',
  'futami mami': '双海真美',
  'futatsuiwa mamizou': '二ッ岩マミゾウ',
  'fuwawa abyssgard': 'フワワ・アビスガード',
  'gamagoori ira': '蒲郡苛',
  'gawr gura': 'がうる・ぐら',
  'genetic (ragnarok online)': 'ジェネティック',
  'gokou ruri': '五更瑠璃',
  'gojou satoru': '五条悟',
  'gotoh futari': '後藤二里',
  'gotoh hitori': '後藤ひとり',
  'goutokuji mike': '豪徳寺ミケ',
  'gundou mirei': '郡道美玲',
  'guy cecil (tales of abyss)': 'ガイ・セシル',
  'hachikuji mayoi': '八九寺真宵',
  'hado nejire': '波動ねじれ',
  'hakurei reimu': '博麗霊夢',
  'hakamada hinata': '袴田ひなた',
  'hamaguchi ayame': '浜口あやめ',
  'hanazono tae': '花園たえ',
  'hanji zoe': 'ハンジ・ゾエ',
  'hatsune miku': '初音ミク',
  'hayasaka ai': '早坂愛',
  'higuchi kaede': '樋口楓',
  'himejima akeno': '姫島朱乃',
  'himemori luna': '姫森ルーナ',
  'himeko (honkai impact)': '姫子',
  'hirasawa yui': '平沢唯',
  'holo (spice and wolf)': 'ホロ',
  'holo (spice and wolf) (spice and wolf)': 'ホロ',
  'hoshimachi suisei': '星街すいせい',
  'hoshino ai': '星野アイ',
  'ichinose kotone': '一ノ瀬ことね',
  'ike (fire emblem)': 'アイク',
  'inaba meguru': '因幡めぐる',
  'inugami korone': '戌神ころね',
  'isigami senku': '石神千空',
  'ishigami yuuta': '石上優',
  'ishigami yuu': '石上優',
  'ishigami yuu (kaguya-sama wa kokurasetai)': '石上優',
  'isla (plastic memories)': 'アイラ',
  'isumi saki': '伊澄サキ',
  'itsuki nakano': '中野五月',
  'jotaro kujo': '空条承太郎',
  'kaguya shinomiya': '四宮かぐや',
  'kaori miyazono': '宮園かをり',
  'kashiwazaki sena': '柏崎星奈',
  'katsuragi keima': '桂木桂馬',
  'kawakami mai': '川神舞',
  'kawashima momo': '川島桃',
  'kirigiri kyoko': '霧切響子',
  'kirisame marisa': '霧雨魔理沙',
  'kiryuin satsuki': '鬼龍院皐月',
  'kisara (engage kiss)': 'キサラ',
  'kitaoji sakurako': '北大路さくら',
  'kitagawa marin': '喜多川海夢',
  'komi shouko': '古見硝子',
  'konata izumi': '泉こなた',
  'koneko toujou': '塔城小猫',
  'kujou sara': '九条裟羅',
  'kurisu makise': '牧瀬紅莉栖',
  'kyouko sakura': '佐倉杏子',
  'laura bodewig': 'ラウラ・ボーデヴィッヒ',
  'lelouch lamperouge': 'ルルーシュ・ランペルージ',
  'levi ackerman': 'リヴァイ',
  'makise kurisu': '牧瀬紅莉栖',
  'makoto niijima': '新島真',
  'maki nishikino': '西木野真姫',
  'maki zenin': '禪院真希',
  'manaka laala': '真中らぁら',
  'mash kyrielight': 'マシュ・キリエライト',
  'matoi ryuuko': '纏流子',
  'mayoi hachikuji': '八九寺真宵',
  'megumin': 'めぐみん',
  'miku nakano': '中野三玖',
  'minami kotori': '南ことり',
  'misaka mikoto': '御坂美琴',
  'miyamoto musashi': '宮本武蔵',
  'miyamura izumi': '宮村伊澄',
  'mordred (fate)': 'モードレッド',
  'mori calliope': '森カリオペ',
  'moriya suwako': '洩矢諏訪子',
  'moss (hololive)': 'ムメイ',
  'nakiri ayame': '百鬼あやめ',
  'nanashi mumei': '七詩ムメイ',
  'natsuiro matsuri': '夏色まつり',
  'nekomata okayu': '猫又おかゆ',
  'ninomae ina\'nis': '一伊那尓栖',
  'nyotengu (dead or alive)': '女天狗',
  'ookami mio': '大神ミオ',
  'oozora subaru': '大空スバル',
  'oshino shinobu': '忍野忍',
  'ouro kronii': 'オーロ・クロニー',
  'pegasus seiya': 'ペガサス星矢',
  'rem (re zero)': 'レム',
  'reimu hakurei': '博麗霊夢',
  'rin tohsaka': '遠坂凛',
  'rory mercury': 'ロゥリィ・マーキュリー',
  'ryuuko matoi': '纏流子',
  'saber (fate)': 'セイバー',
  'sakura miko': 'さくらみこ',
  'sakurajima mai': '桜島麻衣',
  'sawamura spencer eriri': '澤村・スペンサー・英梨々',
  'sena kashiwazaki': '柏崎星奈',
  'shiba miyuki': '司波深雪',
  'shigure ui': 'しぐれうい',
  'shiki ryougi': '両儀式',
  'shimada arisu': '島田愛里寿',
  'shirogane noel': '白銀ノエル',
  'shiranui flare': '不知火フレア',
  'shishiro botan': '獅白ぼたん',
  'shizuka rin': '静凛',
  'sorakado ao': '空門蒼',
  'souryuu asuka langley': '惣流・アスカ・ラングレー',
  'sugimoto saichi': '杉元佐一',
  'sui-feng': '砕蜂',
  'suzumiya haruhi': '涼宮ハルヒ',
  'takagi-san': '高木さん',
  'takanashi kiara': '小鳥遊キアラ',
  'tatsumaki': '戦慄のタツマキ',
  'tifa lockhart': 'ティファ・ロックハート',
  'tohsaka rin': '遠坂凛',
  'todoroki shoto': '轟焦凍',
  'tohru (maidragon)': 'トール',
  'tokoyami towa': '常闇トワ',
  'tomioka giyuu': '冨岡義勇',
  'tsunade (naruto)': '綱手',
  'uchiha itachi': 'うちはイタチ',
  'uchiha madara': 'うちはマダラ',
  'undyne (undertale)': 'アンダイン',
  'usada pekora': '兎田ぺこら',
  'usopp': 'ウソップ',
  'vincent valentine (ff7)': 'ヴィンセント・ヴァレンタイン',
  'watson amelia': 'ワトソン・アメリア',
  'wolverine (x-men)': 'ウルヴァリン',
  'yagami light': '夜神月',
  'yagami taichi': '八神太一',
  'yakumo yukari': '八雲紫',
  'yamada ryo': '山田リョウ',
  'yashiro nene': '八尋寧々',
  'yato (noragami)': '夜ト',
  'yor briar': 'ヨル・フォージャー',
  'yoshizawa kasumi': '芳澤かすみ',
  'yukihana lamy': '雪花ラミィ',
  'yukinoshita yukino': '雪ノ下雪乃',
  'yuzuriha inori': '楪いのり',
  'zhu yuan': '朱鳶',
  poison: 'ポイズン',
  venom: 'ヴェノム',
  'adult neptune': 'ネプテューヌ（大人）',
  'adachi rei': '足立レイ',
  'a-chan': '友人A（えーちゃん）',
  'abarai renji': '阿散井恋次',
  accelerator: '一方通行',
  agumon: 'アグモン',
  'aircraft carrier oni': '空母ヲ級',
  'aircraft carrier water oni': '空母棲鬼',
  'airfield princess': '飛行場姫',
  'battleship princess': '戦艦棲姫',
  'destroyer princess': '駆逐棲姫',
  'aizawa ema': '相沢絵麻',
  'aizawa kazuha': '相沢一葉',
  'akechi gorou': '明智吾郎',
  'akatsuki kirika': '暁切歌',
  'akatsuki uni': '暁宇奈',
  'al azif': 'アル・アジフ',
  'alibaba saluja': 'アリババ・サルージャ',
  'alice margatroid': 'アリス・マーガトロイド',
  'alipheese fateburn xvi': 'アリスフィーズ・フェイトバーン',
  'alisa mikhailovna kujou': 'アリサ・ミハイロヴナ・九条',
  'amity blight': 'アミティ・ブライト',
  angelica: 'アンジェリカ',
  angewomon: 'エンジェウーモン',
  'anyoji hime': '庵歌姫',
  'argalia': 'アルガリア',
  argonians: 'アルゴニアン',
  'arihara nanami': '有原七海',
  'arika yumemiya': '夢宮ありか',
  'arisa bunnings': 'アリサ・バニングス',
  'arisugawa himari': '有栖川ひまり',
  'arisugawa natsuha': '有栖川夏葉',
  'arle nadja': 'アルル・ナジャ',
  'ars almal': 'アルス・アルマル',
  'artem wing': 'アーテム・ウィング',
  arurandeisu: 'アルランディス',
  aruruu: 'アルルゥ',
  'asahina hiyori': '朝比奈日和',
  asgore: 'アズゴア',
  asmodeus: 'アスモデウス',
  assassin: 'アサシン',
  asseylum: 'アセイラム・ヴァース・アリューシア',
  astraea: 'アストレア',
  atri: 'アトリ',
  aty: 'アティ',
  aubrey: 'オーブリー',
  basil: 'バジル',
  'batgirl': 'バットガール',
  'ben tennyson': 'ベン・テニスン',
  'beni-enma': '紅閻魔',
  'bernadetta von varley': 'ベルナデッタ＝フォン＝ヴァーリ',
  'big boss': 'ビッグ・ボス',
  'black heart': 'ブラックハート',
  'if (neptunia)': 'アイエフ',
  'neptune (neptunia)': 'ネプテューヌ',
  'noire (neptunia)': 'ノワール',
  'purple heart (neptunia)': 'パープルハート',
  'uni (neptunia)': 'ユニ',
  'vert (neptunia)': 'ベール',
  'white heart (neptunia)': 'ホワイトハート',
  blackfire: 'ブラックファイヤー',
  blaidd: 'ブライヴ',
  blanc: 'ブラン',
  blossom: 'ブロッサム',
  'boba fett': 'ボバ・フェット',
  bokukawauso: 'ぼくカワウソ',
  'bronya zaychik': 'ブローニャ・ザイチク',
  buneary: 'ミミロル',
  'caesar anthonio zeppeli': 'シーザー・アントニオ・ツェペリ',
  'candice catnipp': 'キャンディス・キャットニップ',
  'carlos oliviera': 'カルロス・オリヴェイラ',
  carnage: 'カーネイジ',
  'cecilia immergreen': 'セシリア・イマーグリーン',
  'celes chere': 'セリス・シェール',
  'centorea shianus': 'セントレア',
  'ceres fauna': 'セレス・ファウナ',
  'chabashira tenko': '茶柱転子',
  'chando': 'チャンド',
  changli: '長離',
  'char aznable': 'シャア・アズナブル',
  chesed: 'ケセド',
  chiester410: 'シエスタ410',
  'chihaya anon': '千早愛音',
  chii: 'ちぃ',
  'chilchuck tims': 'チルチャック・ティムズ',
  'chiyoda momo': '千代田桃',
  'chouzetsusaikawa tenshi-chan': '超絶最かわてんしちゃん',
  'cid highwind': 'シド・ハイウインド',
  'corin wickes': 'カリン・ウィクス',
  crimvael: 'クリムヴェル',
  'cryska barchenowa': 'クリスカ・ビャーチェノワ',
  cthugha: 'クトゥグア',
  'cure chocolat': 'キュアショコラ',
  'cure prism': 'キュアプリズム',
  'cure wonderful': 'キュアワンダフル',
  'daidouji tomoyo': '大道寺知世',
  daiyousei: '大妖精',
  'dana zane': 'ダナ・ゼイン',
  deadpool: 'デッドプール',
  deedlit: 'ディードリット',
  dejiko: 'デ・ジ・キャラット',
  'dennou shoujo siro': '電脳少女シロ',
  'akershus fortress': 'アーケシュフース城',
  'alma armas': 'アルマ・アームズ',
  'alolan vulpix': 'アローラロコン',
  'amae koromo': '天江衣',
  'amagi rinne': '天城燐音',
  'amano pikamee': '天野ピカミィ',
  'anegasaki nene': '姉ヶ崎寧々',
  'archer (fate/samurai remnant)': 'アーチャー',
  archer: 'アーチャー',
  'asseylum vers allusia': 'アセイラム・ヴァース・アリューシア',
  'aura': 'アウラ',
  'aurora sya lis kaymin': 'オーロラ・栖夜・リース・カイミーン',
  'belle': 'リン',
  'boota': 'ブータ',
  'cu chulainn (fate/prototype)': 'クー・フーリン〔プロトタイプ〕',
  death: '死神',
  'diabellstar the black witch': '黒魔女ディアベルスター',
  'doctor doom': 'ドクター・ドゥーム',
  dokibird: 'ドキバード',
  'dokuro-kun': 'ドクロくん',
  'don quixote': 'ドン・キホーテ',
  doomguy: 'ドゥームガイ',
  'dorothy haze': 'ドロシー・ヘイズ',
  dreepy: 'ドラメシヤ',
  'druvis iii': 'ドルーヴィスIII',
  eas: 'イース',
  'ebisu eika': '戎瓔花',
  'ebisuzawa kurumi': '恵飛須沢胡桃',
  'ebizuka tomo': '海老塚智',
  echidna: 'エキドナ',
  'edelgard von hresvelg': 'エーデルガルト＝フォン＝フレスベルグ',
  'edytha rossmann': 'エディータ・ロスマン',
  eevee: 'イーブイ',
  'einhard stratos': 'エインハルト・ストラトス',
  'elaine auclair': 'エレイン・オークレール',
  'elhaym van houten': 'エルハイム・ヴァン・ホーテン',
  'elias ainsworth': 'エリアス・エインズワース',
  elin: 'エリーン',
  'ellen joe': 'エレン・ジョー',
  'endou saya': '遠藤サヤ',
  envy: 'エンヴィー',
  'escha malier': 'エスカ・メーリエ',
  'estellise sidos heurassein': 'エステル',
  'euphyllia magenta': 'ユフィリア・マゼンタ',
  eve: 'イヴ',
  'evelyn chevalier': 'イヴリン・シュヴァリエ',
  exveemon: 'エクスブイモン',
  ezreal: 'エズリアル',
  'falco lombardi': 'ファルコ・ランバルディ',
  faputa: 'ファプタ',
  'faust': 'ファウスト',
  floragato: 'ニャローテ',
  fluttershy: 'フラッターシャイ',
  'fox mccloud': 'フォックス・マクラウド',
  fran: 'フラン',
  'freija crescent': 'フレイヤ・クレセント',
  frieren: 'フリーレン',
  'fu hua': 'フカ',
  'furen e lustario': 'フレン・E・ルスタリオ',
  'futami eriko': '双海絵理',
  "g'raha tia": 'グ・ラハ・ティア',
  garchomp: 'ガブリアス',
  gardevoir: 'サーナイト',
  'garrosh hellscream': 'ガロッシュ・ヘルスクリーム',
  'garrus vakarian': 'ギャラス・ヴァカリアン',
  'gavis bettel': 'ガビス・ベッテル',
  gene: 'ジェネ',
  'gepard landau': 'ジェパード・ランドゥー',
  'getou suguru': '夏油傑',
  'ginko': 'ギンコ',
  'giselle gewelle': 'ジゼル・ジュエル',
  'glamrock freddy': 'グラムロック・フレディ',
  goomba: 'クリボー',
  'grace howard': 'グレース・ハワード',
  'grayfia lucifuge': 'グレイフィア・ルシファー',
  'grea': 'グレア',
  'gregor': 'グレゴール',
  greymon: 'グレイモン',
  'guido mista': 'グイード・ミスタ',
  'gurren-lagann': 'グレンラガン',
  'gwen tennyson': 'グウェン・テニスン',
  gwendolyn: 'グウェンドリン',
  'hakase fuyuki': '博士冬樹',
  'hakozaki serika': '箱崎星梨花',
  'hanami saki': '花海咲季',
  'hanami ume': '花海佑芽',
  'hanamura yousuke': '花村陽介',
  'hanasaki tsubomi': '花咲つぼみ',
  'handa roco': '半田ロコ',
  hanyuu: '羽入',
  'harukawa maki': '春川魔姫',
  'haruno haruka': '春野はるか',
  'haruno sakura': '春野サクラ',
  'hasegawa kobato': '長谷川小鳩',
  'hashibira inosuke': '嘴平伊之助',
  'hata no kokoro': '秦こころ',
  'hatsume mei': '発目明',
  'hayakawa aki': '早川アキ',
  'hazuki ren': '葉月恋',
  'heanna sumire': '平安名すみれ',
  'heiwajima shizuo': '平和島静雄',
  'hero': '勇者',
  'heroine': 'ヒロイン',
  'heshikiri hasebe': 'へし切長谷部',
  'hieda no akyuu': '稗田阿求',
  'higashi setsuna': '東せつな',
  'higashiyama kobeni': '東山コベニ',
  higekiri: '髭切',
  'hiiragi tsukasa': '柊つかさ',
  'hiiragi utena': '柊うてな',
  'hiiragi yuzu': '柊柚子',
  'hijiri ageha': '聖あげは',
  'hijiri byakuren': '聖白蓮',
  'hikami sumire': '氷上スミレ',
  'hikawa iona': '氷川いおな',
  'hikawa sayo': '氷川紗夜',
  'himemiya chikane': '姫宮千歌音',
  'himemiya tori': '姫宮桃李',
  'airani iofifteen': 'アイラニ・イオフィフティーン',
  'aki rosenthal': 'アキ・ローゼンタール',
  'akai haato': '赤井はあと',
  'azki': 'AZKi',
  'ayunda risu': 'アユンダ・リス',
  'banzoin hakka': '万象院ハッカ',
  'ceres fauna': 'セレス・ファウナ',
  'cecilia immergreen': 'セシリア・イマーグリーン',
  'fallenshadow': 'ファレン・シャドウ',
  'gigi murin': 'ジジ・ムリン',
  'hakos baelz': 'ハコス・ベールズ',
  'mococo abyssgard': 'モココ・アビスガード',
  'mori calliope': '森カリオペ',
  'vestia zeta': 'ベスティア・ゼータ',
  'shiori novella': 'シオリ・ノヴェラ',
  'yuzuki choco': '癒月ちょこ',
};

// Second-pass corrections for common Japanese names that the upstream alias
// file leaves in romanized form. These are written into character_names.json;
// they are not runtime overrides.
Object.assign(GLOBAL_NAMES, {
  'ayase yue': '綾瀬夕映',
  'hino rei': '火野レイ',
  'hinata shouyou': '日向翔陽',
  'hirasawa ui': '平沢憂',
  'hoto cocoa': '保登心愛',
  'houjou satoko': '北条沙都子',
  'hououji fuu': '鳳凰寺風',
  'houraisan kaguya': '蓬莱山輝夜',
  'hyakumantenbara salome': '壱百満天原サロメ',
  'iida tenya': '飯田天哉',
  'ijichi nijika': '伊地知虹夏',
  'ibuki suika': '伊吹萃香',
  'iizunamaru megumu': '飯綱丸龍',
  'inaba tewi': '因幡てゐ',
  'inoue orihime': '井上織姫',
  'inubashiri momiji': '犬走椛',
  'izayoi liko': '十六夜リコ',
  'izayoi sakuya': '十六夜咲夜',
  'izumi sagiri': '和泉紗霧',
  'jakuzure nonon': '蛇崩乃音',
  jigglypuff: 'プリン',
  'jing yuan': '景元',
  'jirou kyouka': '耳郎響香',
  'jonouchi katsuya': '城之内克也',
  'joutouguu mayumi': '杖刀偶磨弓',
  'kaenbyou rin': '火焔猫燐',
  'kafuu chino': '香風智乃',
  'kagurazaka asuna': '神楽坂明日菜',
  'kaguya luna': '輝夜月',
  'kakyouin noriaki': '花京院典明',
  'kakyoin noriaki': '花京院典明',
  'kamado nezuko': '竈門禰豆子',
  'kaneki ken': '金木研',
  'kanzaki kaori': '神裂火織',
  'kasane teto': '重音テト',
  'katou megumi': '加藤恵',
  'kinomoto sakura': '木之本桜',
  'kiryu coco': '桐生ココ',
  'kikuchi makoto': '菊地真',
  'kisaragi chihaya': '如月千早',
  'kishibe rohan': '岸辺露伴',
  'kita ikuyo': '喜多郁代',
  'kitashirakawa anko': '北白川あんこ',
  'kochiya sanae': '東風谷早苗',
  'kochou shinobu': '胡蝶しのぶ',
  'koizumi hanayo': '小泉花陽',
  'koiwai yotsuba': '小岩井よつば',
  'kotobuki tsumugi': '琴吹紬',
  'kuki shinobu': '久岐忍',
  'kuriyama mirai': '栗山未来',
  'kuroba kaito': '黒羽快斗',
  'kurosaki ichigo': '黒崎一護',
  'kururugi suzaku': '枢木スザク',
  'kusanagi motoko': '草薙素子',
  'kuroyukihime': '黒雪姫',
  'maekawa miku': '前川みく',
  'maruyama aya': '丸山彩',
  'matsumoto rangiku': '松本乱菊',
  'matsuno choromatsu': '松野チョロ松',
  'matsuno osomatsu': '松野おそ松',
  'matsuno todomatsu': '松野トド松',
  'midoriya izuku': '緑谷出久',
  'mine fujiko': '峰不二子',
  'mizuhashi parsee': '水橋パルスィ',
  'mogami shizuka': '最上静香',
  'morishima haruka': '森島はるか',
  'naganohara mio': '長野原みお',
  'nakano azusa': '中野梓',
  'nakano ichika': '中野一花',
  'nakano itsuki': '中野五月',
  'nakano miku': '中野三玖',
  nekomusume: '猫娘',
  'nishizono mio': '西園美魚',
  'nozaki umetarou': '野崎梅太郎',
  'okazaki tomoya': '岡崎朋也',
  'okazaki yumemi': '岡崎夢美',
  'osana najimi': '長名なじみ',
  'shameimaru aya': '射命丸文',
  'shanghai doll': '上海人形',
  'shibuya rin': '渋谷凛',
  'shinigami': '死神',
  'son goku': '孫悟空',
  'tanaka kotoha': '田中琴葉',
  'tanaka mamimi': '田中摩美々',
  'takanashi rikka': '小鳥遊六花',
  'uesugi fuutarou': '上杉風太郎',
  'urushibara ruka': '漆原るか',
  'yamamura sadako': '山村貞子',
  'yamanaka sawako': '山中さわ子',
  'yasaka kanako': '八坂神奈子',
  'yuuki makoto (persona 3)': '結城理',
  'mr. squeaks (hakos baelz)': 'Mr. Squeaks',
  'hisako fuchida (angel beats!)': 'ひさ子',
  'sekine shiori (angel beats!)': '関根しおり',
  'hitsugaya toushirou (bleach)': '日番谷冬獅郎',
  'ishida uryuu (bleach)': '石田雨竜',
  'kurotsuchi nemu (bleach)': '涅ネム',
  'nelliel tu odelschwanck (bleach)': 'ネリエル・トゥ・オーデルシュヴァンク',
  'tier harribel (bleach)': 'ティア・ハリベル',
  'angela (project moon)': 'アンジェラ',
  'angelica (project moon)': 'アンジェリカ',
  'argalia (project moon)': 'アルガリア',
  'binah (project moon)': 'ビナー',
  'carmen (project moon)': 'カルメン',
  'chesed (project moon)': 'ケセド',
  'don quixote (project moon)': 'ドン・キホーテ',
  'faust (project moon)': 'ファウスト',
  'gebura (project moon)': 'ゲブラー',
  'gregor (project moon)': 'グレゴール',
  'hod (project moon)': 'ホド',
  'ishmael (project moon)': 'イシュメール',
  'malkuth (project moon)': 'マルクト',
  'netzach (project moon)': 'ネツァク',
  'roland (project moon)': 'ローラン',
  'ryoshu (project moon)': '良秀',
  'sinclair (project moon)': 'シンクレア',
  'tiphereth a (project moon)': 'ティファレト',
  'yi sang (project moon)': 'イサン',
  'yesod (project moon)': 'イェソド',
  'gaara (naruto)': '我愛羅',
  'hyuuga hanabi (naruto)': '日向ハナビ',
  'hyuuga neji (naruto)': '日向ネジ',
  'crocodile (one piece)': 'クロコダイル',
  'jinbe (one piece)': 'ジンベエ',
  'puck (re zero)': 'パック',
  'may (guilty gear)': 'メイ',
  'testament (guilty gear)': 'テスタメント',
  'tarnished (elden ring)': '褪せ人',
  'justice (helltaker)': 'ジャスティス',
  'modeus (helltaker)': 'モデウス',
  'ms. fortune (skullgirls)': 'ミス・フォーチュン',
  'kawasumi mai (kanon)': '川澄舞',
  'tsukimiya ayu (kanon)': '月宮あゆ',
  'nero claudius (fate/extra)': 'ネロ・クラウディウス',
  'tamamo no mae (fate/extra)': '玉藻の前',
  'jane doe (zenless zone zero)': 'ジェーン・ドゥ',
  'qingyi (zenless zone zero)': '青衣',
  'fujimaru ritsuka (female) (decisive battle chaldea uniform)': '藤丸立香（女性）（決戦用カルデア制服）',
  'fujimaru ritsuka (male) (decisive battle chaldea uniform)': '藤丸立香（男性）（決戦用カルデア制服）',
  'fujimaru ritsuka (female) (polar chaldea uniform)': '藤丸立香（女性）（極地用カルデア制服）',
  'fujimaru ritsuka (male) (polar chaldea uniform)': '藤丸立香（男性）（極地用カルデア制服）',
  'iwatooshi (touken ranbu)': '岩融',
  'igarashi futaba (shiromanta)': '五十嵐双葉',
  'takeda harumi (shiromanta)': '武田晴海',
  'kaf (kamitsubaki studio)': '花譜',
  'rim (kamitsubaki studio)': '理芽',
  'kafu (cevio)': '可不',
  'one (cevio)': 'ONE',
  'kim possible (kim possible)': 'キム・ポッシブル',
  'shego (kim possible)': 'シーゴ',
  'master chief (halo)': 'マスターチーフ',
  'sangheili (halo)': 'サンヘイリ',
  'miyu edelfelt (magical girl)': '美遊・エーデルフェルト',
  'momoe nagisa (magical girl)': '百江なぎさ',
  'sakamata chloe (jirai kei)': '沙花叉クロヱ',
  'chii (chobits)': 'ちぃ',
  'crewmate (among us)': 'クルーメイト',
  'kiana kaslana (herrscher of finality)': 'キアナ・カスラーナ',
  'hoshiguma yuugi (kimono)': '星熊勇儀',
  'horkeu kamui (tokyo afterschool summoners)': 'ホロケウカムイ',
  'hoshino yumemi (planetarian)': '星野夢美',
  'illyasviel von einzbern (swimsuit archer)': 'イリヤスフィール・フォン・アインツベルン',
  'kamisato ayaka (springbloom missive)': '神里綾華',
  'kratos (god of war)': 'クレイトス',
  'krile mayer baldesion (ff5)': 'クルル・マイア・バルデシオン',
  'kurumi (lycoris recoil)': 'クルミ',
  'legoshi (beastars)': 'レゴシ',
  'leo (fire emblem fates)': 'レオン',
  'linne (under night in-birth)': 'リンネ',
  'little mac (punch out)': 'リトル・マック',
  'manya (dq4)': 'マーニャ',
  'may (gundam build divers re rise)': 'メイ',
  'meiko (vocaloid)': 'MEIKO',
  'mew ichigo (tokyo mew mew)': 'ミュウイチゴ',
  'mieu (tales of the abyss)': 'ミュウ',
  'min min (arms)': 'ミェンミェン',
  'mita (miside)': 'ミタ',
  'naoki miki (gakkou gurashi!)': '直樹美紀',
  'nekomusume (gegege no kitarou)': 'ねこ娘',
  'nick wilde (zootopia)': 'ニック・ワイルド',
  'optimus prime (transformers)': 'オプティマスプライム',
  'osana najimi (komi-san wa komyushou desu)': '長名なじみ',
  'puniru (puniru wa kawaii slime)': 'ぷにる',
  'pyramid head (silent hill)': '三角頭',
  'raiden mei (herrscher of origin)': '雷電芽衣',
  'raiden mei (herrscher of thunder)': '雷電芽衣',
  'raphael (tmnt)': 'ラファエロ',
  'rarity (my little pony)': 'ラリティ',
  'red blood cell (hataraku saibou)': '赤血球',
  'red riding hood (sinoalice)': '赤ずきん',
  'reisen (touhou bougetsushou)': '鈴仙・優曇華院・イナバ',
  'renne (eiyuu densetsu)': 'レン',
  'ridley (metroid)': 'リドリー',
  'rukawa kaede (slam dunk)': '流川楓',
  'sango (inuyasha)': '珊瑚',
  'saria (zelda)': 'サリア',
  'saya (saya no uta)': '沙耶',
  'senko (sewayaki kitsune no senko-san)': '仙狐',
  'sensei (blue archive the animation)': '先生',
  'shiina mahiru (otonari no tenshi-sama)': '椎名真昼',
  'shimura shinpachi (gin tama)': '志村新八',
  'sylphiette (mushoku tensei)': 'シルフィエット',
  'urushibara ruka (steins gate)': '漆原るか',
  'venat (ff14)': 'ヴェーネス',
  'vertin (reverse 1999)': 'ヴェルティ',
  'vita (nanoha)': 'ヴィータ',
  'walpurgisnacht (madoka magica)': 'ワルプルギスの夜',
  'yuuri (shoujo shuumatsu ryokou)': 'ユーリ',
});

const KANCOLLE = {
  abukuma: '阿武隈', admiral: '提督', agano: '阿賀野', akagi: '赤城', akashi: '明石',
  akatsuki: '暁', akebono: '曙', akigumo: '秋雲', akishimo: '秋霜', 'akitsu maru': 'あきつ丸',
  akitsushima: '秋津洲', akizuki: '秋月', amagi: '天城', amagiri: '天霧', amatsukaze: '天津風',
  aoba: '青葉', aquila: 'アクィラ', arashi: '嵐', arashio: '荒潮', 'ark royal': 'アーク・ロイヤル',
  asagumo: '朝雲', asakaze: '朝風', asashimo: '朝霜', asashio: '朝潮', ashigara: '足柄',
  atago: '愛宕', atlanta: 'アトランタ', ayanami: '綾波', bismarck: 'ビスマルク', chikuma: '筑摩',
  chitose: '千歳', chiyoda: '千代田', chougei: '長鯨', choukai: '鳥海', colorado: 'コロラド',
  'commandant teste': 'コマンダン・テスト', 'conte di cavour': 'コンテ・ディ・カブール', daitou: '大東',
  'de ruyter': 'デ・ロイテル', etorofu: '択捉', fletcher: 'フレッチャー', 'fletcher mk ii': 'フレッチャー',
  fubuki: '吹雪', fujinami: '藤波', fukae: '福江', fumizuki: '文月', furutaka: '古鷹', fusou: '扶桑',
  fuyutsuki: '冬月', 'gambier bay': 'ガンビア・ベイ', gangut: 'ガングート', gotland: 'ゴトランド',
  'graf zeppelin': 'グラーフ・ツェッペリン', grecale: 'グレカーレ', hachijou: '八丈', hagikaze: '萩風',
  haguro: '羽黒', hamakaze: '浜風', hamanami: '浜波', harukaze: '春風', haruna: '榛名', harusame: '春雨',
  hatakaze: '旗風', hatsuharu: '初春', hatsukaze: '初風', hatsushimo: '初霜', hatsuyuki: '初雪',
  hatsuzuki: '初月', hayanami: '早波', hayashimo: '早霜', hayashio: '早潮', hayasui: '速吸',
  helena: 'ヘレナ', hibiki: '響', hiei: '比叡', hirato: '平戸', hiryuu: '飛龍', hiyou: '飛鷹',
  honolulu: 'ホノルル', hornet: 'ホーネット', houshou: '鳳翔', houston: 'ヒューストン', hyuuga: '日向',
  'i-168': '伊168', 'i-19': '伊19', 'i-203': '伊203', 'i-26': '伊26', 'i-401': '伊401', 'i-47': '伊47',
  'i-58': '伊58', 'i-8': '伊8', ikazuchi: '雷', inazuma: '電', intrepid: 'イントレピッド', iowa: 'アイオワ',
  irako: '伊良湖', ise: '伊勢', isokaze: '磯風', isonami: '磯波', isuzu: '五十鈴', janus: 'ジャーヴィス',
  jervis: 'ジャーヴィス', jingei: '迅鯨', jintsuu: '神通', johnston: 'ジョンストン', "jun'you": '隼鷹',
  kaga: '加賀', kagerou: '陽炎', kako: '加古', kamikaze: '神風', kamoi: '神威', kashima: '鹿島',
  katori: '香取', katsuragi: '葛城', kawakaze: '江風', kazagumo: '風雲', kikuzuki: '菊月', kinugasa: '衣笠',
  kirishima: '霧島', kisaragi: '如月', kiso: '木曾', kitakami: '北上', kiyoshimo: '清霜', kongou: '金剛',
  kuma: '球磨', kumano: '熊野', kunashiri: '国後', kuroshio: '黒潮', libeccio: 'リベッチオ', littorio: 'リットリオ',
  'luigi di savoia duca degli abruzzi': 'ルイージ・ディ・サヴォイア・ドゥーカ・デッリ・アブルッツィ',
  'luigi torelli': 'ルイージ・トレッリ', maestrale: 'マエストラーレ', maikaze: '舞風', makigumo: '巻雲',
  mamiya: '間宮', 'maru-yu': 'まるゆ', maryland: 'メリーランド', maya: '摩耶', michishio: '満潮',
  mikazuki: '三日月', mikuma: '三隈', mikura: '御蔵', minegumo: '峯雲', miyuki: '深雪', mizuho: '瑞穂',
  mochizuki: '望月', mogami: '最上', murakumo: '叢雲', murasame: '村雨', musashi: '武蔵', mutsu: '陸奥',
  mutsuki: '睦月', myoukou: '妙高', nachi: '那智', naganami: '長波', nagara: '長良', nagato: '長門',
  nagatsuki: '長月', naka: '那珂', nelson: 'ネルソン', nenohi: '子日', nisshin: '日進', noshiro: '能代',
  nowaki: '野分', oboro: '朧', ooi: '大井', ooshio: '大潮', ooyodo: '大淀', oyashio: '親潮', perth: 'パース',
  pola: 'ポーラ', 'prinz eugen': 'プリンツ・オイゲン', ranger: 'レンジャー', richelieu: 'リシュリュー',
  'ro-500': '呂500', roma: 'ローマ', ryuuhou: '龍鳳', ryuujou: '龍驤', sagiri: '狭霧', sakawa: '酒匂',
  samidare: '五月雨', 'samuel b. roberts': 'サミュエル・B・ロバーツ', saratoga: 'サラトガ', satsuki: '皐月',
  sazanami: '漣', scamp: 'スキャンプ', scirocco: 'シロッコ', sendai: '川内', sheffield: 'シェフィールド',
  shigure: '時雨', shikinami: '敷波', shimakaze: '島風', shimushu: '占守', "shin'you": '神鷹',
  'shinshuu maru': '神州丸', shiranui: '不知火', shiratsuyu: '白露', shirayuki: '白雪', shouhou: '祥鳳',
  shoukaku: '翔鶴', souryuu: '蒼龍', 'south dakota': 'サウスダコタ', suzukaze: '涼風', suzutsuki: '涼月',
  suzuya: '鈴谷', taigei: '大鯨', taihou: '大鳳', takanami: '高波', takao: '高雄', tama: '多摩',
  tanikaze: '谷風', tashkent: 'タシュケント', tatsuta: '龍田', tenryuu: '天龍', teruzuki: '照月',
  tokitsukaze: '時津風', tone: '利根', tsushima: '対馬', 'u-511': 'U-511', umikaze: '海風', unryuu: '雲龍',
  urakaze: '浦風', ushio: '潮', usugumo: '薄雲', uzuki: '卯月', verniy: 'Верный', wakaba: '若葉',
  warspite: 'ウォースパイト', washington: 'ワシントン', yahagi: '矢矧', yamagumo: '山雲', yamakaze: '山風',
  yamashiro: '山城', yamato: '大和', yayoi: '弥生', yukikaze: '雪風', yura: '由良', yuubari: '夕張',
  yuudachi: '夕立', yuugumo: '夕雲', 'z1 leberecht maass': 'Z1 レーベレヒト・マース', 'z3 max schultz': 'Z3 マックス・シュルツ',
  zara: 'ザラ', zuihou: '瑞鳳', zuikaku: '瑞鶴',
};

const FATE = {
  abigail: 'アビゲイル・ウィリアムズ', 'abigail williams': 'アビゲイル・ウィリアムズ', altera: 'アルテラ',
  'amakusa shirou': '天草四郎', anastasia: 'アナスタシア', 'anne bonny': 'アン・ボニー',
  'antonio salieri': 'アントニオ・サリエリ', archer: 'アーチャー', arjuna: 'アルジュナ', 'arjuna alter': 'アルジュナ〔オルタ〕',
  'arthur pendragon': 'アーサー・ペンドラゴン', 'artoria caster': 'アルトリア・キャスター', 'artoria pendragon': 'アルトリア・ペンドラゴン',
  asclepius: 'アスクレピオス', 'ashiya douman': '蘆屋道満', astolfo: 'アストルフォ', atalanta: 'アタランテ',
  'atalanta alter': 'アタランテ〔オルタ〕', 'baobhan sith': 'バーヴァン・シー', barghest: 'バーゲスト', bb: 'BB',
  'bb dubai': 'BBドバイ', bedivere: 'ベディヴィエール', boudica: 'ブーディカ', bradamante: 'ブラダマンテ',
  brynhild: 'ブリュンヒルデ', caenis: 'カイニス', 'captain nemo': 'キャプテン・ネモ', carmilla: 'カーミラ', aesc: 'トネリコ',
  chacha: '茶々', 'charlotte corday': 'シャルロット・コルデー', "chevalier d'eon": 'シュヴァリエ・デオン', circe: 'キルケー',
  'cu chulainn': 'クー・フーリン', 'diarmuid ua duibhne': 'ディルムッド・オディナ', 'dobrynya nikitich': 'ドブルイニャ・ニキチッチ',
  'edward teach': 'エドワード・ティーチ', 'elizabeth bathory': 'エリザベート・バートリー', enkidu: 'エルキドゥ',
  ereshkigal: 'エレシュキガル', euryale: 'エウリュアレ', 'florence nightingale': 'ナイチンゲール', fou: 'フォウ',
  "frankenstein's monster": 'フランケンシュタイン', 'fuuma kotarou': '風魔小太郎', gareth: 'ガレス', gilgamesh: 'ギルガメッシュ',
  'gilles de rais': 'ジル・ド・レェ', gorgon: 'ゴルゴーン', gray: 'グレイ', habetrot: 'ハベトロット',
  'hassan of serenity': '静謐のハサン', hector: 'ヘクトール', 'helena blavatsky': 'ブラヴァツキー', hildr: 'ヒルド',
  'ibaraki douji': '茨木童子', 'ibuki douji': '伊吹童子', ishtar: 'イシュタル', iskandar: 'イスカンダル',
  'jeanne d\'arc': 'ジャンヌ・ダルク', 'jeanne d\'arc alter': 'ジャンヌ・ダルク〔オルタ〕', kama: 'カーマ', karna: 'カルナ',
  'katou danzou': '加藤段蔵', 'katsushika hokusai': '葛飾北斎', kingprotea: 'キングプロテア', kiyohime: '清姫',
  koyanskaya: 'コヤンスカヤ', kukulkan: 'ククルカン', 'lady avalon': 'レディ・アヴァロン', 'leonardo da vinci': 'レオナルド・ダ・ヴィンチ',
  'marie antoinette': 'マリー・アントワネット', martha: 'マルタ', 'mary read': 'メアリー・リード', medb: 'メイヴ',
  medea: 'メディア', medusa: 'メドゥーサ', meltryllis: 'メルトリリス', melusine: 'メリュジーヌ', merlin: 'マーリン',
  'minamoto no raikou': '源頼光', 'miyamoto musashi': '宮本武蔵', 'mochizuki chiyome': '望月千代女', mordred: 'モードレッド',
  'morgan le fay': 'モルガン', 'murasaki shikibu': '紫式部', 'mysterious heroine x': '謎のヒロインX',
  'nagao kagetora': '長尾景虎', 'napoleon bonaparte': 'ナポレオン', nero: 'ネロ・クラウディウス', 'nero claudius': 'ネロ・クラウディウス',
  nitocris: 'ニトクリス', 'nursery rhyme': 'ナーサリー・ライム', oberon: 'オベロン', 'oda nobunaga': '織田信長',
  'okada izou': '岡田以蔵', 'okita souji': '沖田総司', 'okita j. souji': '沖田J総司', osakabehime: '刑部姫',
  parvati: 'パールヴァティー', passionlip: 'パッションリップ', 'paul bunyan': 'ポール・バニヤン', penthesilea: 'ペンテシレイア',
  'prince of lan ling': '蘭陵王', quetzalcoatl: 'ケツァル・コアトル', saber: 'セイバー', 'saitou hajime': '斎藤一',
  scathach: 'スカサハ', 'scathach skadi': 'スカサハ＝スカディ', 'sei shounagon': '清少納言', semiramis: 'セミラミス',
  'shuten douji': '酒呑童子', sieg: 'ジーク', sitonai: 'シトナイ', 'space ishtar': 'スペース・イシュタル',
  stheno: 'ステンノ', 'suzuka gozen': '鈴鹿御前', 'tamamo cat': '玉藻の前〔タマモキャット〕', 'tamamo no mae': '玉藻の前',
  tiamat: 'ティアマト', 'tomoe gozen': '巴御前', ushiwakamaru: '牛若丸', 'wolfgang amadeus mozart': 'ヴォルフガング・アマデウス・モーツァルト',
  'wu zetian': '武則天', 'xuangzang sanzang': '玄奘三蔵', 'yamato takeru': 'ヤマトタケル', 'yang guifei': '楊貴妃',
  'yu mei-ren': '虞美人', 'yui shousetsu': '由井正雪', zenobia: 'ゼノビア',
};

const BLUE_ARCHIVE = {
  airi: '栗村アイリ', akane: '室笠アカネ', ako: '天雨アコ', aris: '天童アリス', arona: 'アロナ', aru: '陸八魔アル',
  asuna: '一之瀬アスナ', atsuko: '秤アツコ', ayane: '奥空アヤネ', azusa: '白洲アズサ', cherino: '連河チェリノ',
  chihiro: '各務チヒロ', chinatsu: '火宮チナツ', chise: '和楽チセ', eimi: '才羽エイミ', fuuka: '愛清フウカ',
  hanae: '朝顔ハナエ', hanako: '浦和ハナコ', hare: '小鈎ハレ', haruka: '伊草ハルカ', haruna: '黒舘ハルナ',
  hasumi: '羽川ハスミ', hibiki: '猫塚ヒビキ', hifumi: '阿慈谷ヒフミ', himari: '明星ヒマリ', hina: '空崎ヒナ',
  hinata: '若葉ヒナタ', hiyori: '槌永ヒヨリ', hoshino: '小鳥遊ホシノ', ibuki: '丹花イブキ', ichika: '仲正イチカ',
  iori: '銀鏡イオリ', iroha: '棗イロハ', izumi: '獅子堂イズミ', izuna: '久田イズナ', junko: '赤司ジュンコ',
  kaho: '朝比奈カホ', kanna: '尾刃カンナ', karin: '角楯カリン', kayoko: '鬼方カヨコ', kazusa: '杏山カズサ',
  kirino: '中務キリノ', kisaki: '勘解由小路キサキ', koharu: '下江コハル', kokona: '春原ココナ', kotama: '音瀬コタマ',
  kotori: '豊見コトリ', koyuki: '黒崎コユキ', maki: '小塗マキ', makoto: '羽沼マコト', mari: '伊落マリー',
  marina: '池倉マリナ', mashiro: '静山マシロ', midori: '才羽ミドリ', mina: '中務ミナ', miyako: '月雪ミヤコ',
  miyu: '霞沢ミユ', moe: '風倉モエ', momoi: '才羽モモイ', mutsuki: '浅黄ムツキ', nagisa: '桐藤ナギサ',
  natsu: '柚鳥ナツ', neru: '美甘ネル', noa: '生塩ノア', nonomi: '十六夜ノノミ', plana: 'プラナ',
  rio: '調月リオ', saki: '空井サキ', saori: '錠前サオリ', seia: '百合園セイア', serika: '黒見セリカ',
  serina: '鷲見セリナ', shiroko: '砂狼シロコ', shun: '春原シュン', toki: '飛鳥馬トキ', ui: '古関ウイ',
  utaha: '白石ウタハ', wakamo: '狐坂ワカモ', yoshimi: '伊原木ヨシミ', yuuka: '早瀬ユウカ', yuzu: '花岡ユズ',
};

const ARKNIGHTS = {
  amiya: 'アーミヤ', angelina: 'アンジェリーナ', ansel: 'アンセル', archetto: 'アルケット', astesia: 'アステシア',
  aurora: 'オーロラ', bagpipe: 'バグパイプ', beanstalk: 'ビーンストーク', beeswax: 'ビーズワクス', blaze: 'ブレイズ',
  blemishine: 'ブレミシャイン', 'blue poison': 'ブルーポイズン', carnelian: 'カーネリアン', ceobe: 'ケオベ', ceylon: 'セイロン',
  "ch'en": 'チェン', 'chong yue': 'チョンユエ', cliffheart: 'クリフハート', closure: 'クロージャ', croissant: 'クロワッサン',
  degenbrecher: 'デーゲンブレヒャー', dobermann: 'ドーベルマン', doctor: 'ドクター', dorothy: 'ドロシー', dusk: '夕',
  ebenholz: 'エーベンホルツ', elysium: 'エリジウム', eunectes: 'ユーネクテス', exusiai: 'エクシア', eyjafjalla: 'エイヤフィヤトラ',
  fartooth: 'ファートゥース', fiammetta: 'フィアメッタ', flametail: 'フレイムテイル', franka: 'フランカ', frostleaf: 'フロストリーフ',
  frostnova: 'フロストノヴァ', gavial: 'ガヴィル', gladiia: 'グラディア', glaucus: 'グラウコス', goldenglow: 'ゴールデングロー',
  grani: 'グラニ', gravel: 'グラベル', gummy: 'グム', harmonie: 'ハーモニー', hibiscus: 'ハイビスカス', horn: 'ホルン',
  hoshiguma: 'ホシグマ', hung: 'ウン', ifrit: 'イフリータ', ines: 'イネス', irene: 'アイリーニ', istina: 'イースチナ',
  jessica: 'ジェシカ', "kal'tsit": 'ケルシー', kroos: 'クルース', la_pluma: 'ラ・プルマ', lappland: 'ラップランド',
  lava: 'ラヴァ', lee: 'リー', lin: 'リン', ling: 'リィン', liskarm: 'リスカム', logos: 'ロゴス', lumen: 'ルーメン',
  magallan: 'マゼラン', manticore: 'マンティコア', mizuki: 'ミヅキ', mostima: 'モスティマ', mountain: 'マウンテン',
  mudrock: 'マドロック', muelsyse: 'ミュルジス', mulberry: 'マルベリー', myrtle: 'テンニンカ', nearl: 'ニアール',
  nian: 'ニェン', nightingale: 'ナイチンゲール', pallas: 'パラス', penance: 'ペナンス', perfumer: 'パフューマー',
  phantom: 'ファントム', pinecone: 'パインコーン', platinum: 'プラチナ', pozyomka: 'ポデンコ', pramanix: 'プラマニクス',
  'projekt red': 'レッド', provence: 'プロヴァンス', ptilopsis: 'フィリオプシス', reed: 'リード', robin: 'ロビン',
  rosa: 'ロサ', rosmontis: 'ロスモンティス', saga: 'サガ', saileach: 'サイラッハ', saria: 'サリア', schwarz: 'シュヴァルツ',
  shamare: 'シャマレ', shaw: 'ショウ', shining: 'シャイニング', shu: 'シュウ', siege: 'シージ', silence: 'サイレンス',
  skadi: 'スカジ', skyfire: 'スカイフレア', sora: 'ソラ', specter: 'スペクター', surtr: 'スルト', sussurro: 'ススーロ',
  suzuran: 'スズラン', swire: 'スワイヤー', talulah: 'タルラ', tequila: 'テキーラ', texas: 'テキサス', theresa: 'テレジア',
  thorns: 'ソーンズ', tomimi: 'トミミ', typhon: 'ティフォン', utage: 'ウタゲ', vermeil: 'ヴァーミル', vigna: 'ヴィグナ',
  virtuosa: 'ヴィルトゥオーサ', viviana: 'ヴィヴィアナ', warfarin: 'ワルファリン', weedy: 'ウィーディ', whisperain: 'ウィスパーレイン', zima: 'ズィマー',
};

const AZUR_LANE = {
  abercrombie: 'アバークロンビー', 'admiral graf spee': 'アドミラル・グラーフ・シュペー', 'admiral hipper': 'アドミラル・ヒッパー',
  aegir: 'エーギル', ajax: 'エイジャックス', akagi: '赤城', 'akagi-chan': '赤城ちゃん', akashi: '明石', alabama: 'アラバマ',
  albacore: 'アルバコア', amagi: '天城', 'amagi-chan': '天城ちゃん', anchorage: 'アンカレッジ', 'ark royal': 'アーク・ロイヤル',
  atago: '愛宕', 'august von parseval': 'アウグスト・フォン・パーセヴァル', ayanami: '綾波', azuma: '吾妻', bache: 'ベイリー',
  baltimore: 'ボルチモア', bataan: 'バターン', belfast: 'ベルファスト', bellona: 'ベローナ', bismarck: 'ビスマルク',
  bremerton: 'ブレマートン', chapayev: 'チャパエフ', 'chen hai': '鎮海', cheshire: 'チェシャー', choukai: '鳥海', cleveland: 'クリーブランド',
  cygnet: 'シグニット', deutschland: 'ドイッチュラント', dido: 'ダイドー', dunkerque: 'ダンケルク', elbe: 'エルベ', elbing: 'エルビング',
  eldridge: 'エルドリッジ', enterprise: 'エンタープライズ', erebus: 'エレバス', essex: 'エセックス', foch: 'フォッシュ', formidable: 'フォーミダブル',
  'friedrich der grosse': 'フリードリヒ・デア・グローセ', gascogne: 'ガスコーニュ', gneisenau: 'グナイゼナウ', 'graf zeppelin': 'グラーフ・ツェッペリン',
  hakuryuu: '白龍', hammann: 'ハムマン', helena: 'ヘレナ', hindenburg: 'ヒンデンブルク', honolulu: 'ホノルル', hornet: 'ホーネット',
  illustrious: 'イラストリアス', implacable: 'インプラカブル', indianapolis: 'インディアナポリス', indomitable: 'インドミタブル', javelin: 'ジャベリン',
  'jean bart': 'ジャン・バール', kaga: '加賀', kawakaze: '江風', kearsarge: 'キアサージ', kisaragi: '如月', kronshtadt: 'クロンシュタット',
  laffey: 'ラフィー', 'le malin': 'ル・マラン', 'little bel': 'リトル・ベル', littorio: 'リットリオ', mary: 'メアリー・セレステ',
  'mary celeste': 'メアリー・セレステ', massachusetts: 'マサチューセッツ', mikasa: '三笠', minneapolis: 'ミネアポリス', monarch: 'モナーク', musashi: '武蔵',
  mutsuki: '睦月', nagato: '長門', nelson: 'ネルソン', neptune: 'ネプチューン', 'new jersey': 'ニュージャージー', 'ning hai': '寧海',
  'north carolina': 'ノースカロライナ', noshiro: '能代', owari: '尾張', 'pamiat merkuria': 'パーミャチ・メルクーリヤ', perseus: 'パーシュース',
  'ping hai': '平海', plymouth: 'プリマス', pola: 'ポーラ', portland: 'ポートランド', 'prince of wales': 'プリンス・オブ・ウェールズ',
  'prinz adalbert': 'プリンツ・アーダルベルト', 'prinz eugen': 'プリンツ・オイゲン', 'prinz heinrich': 'プリンツ・ハインリヒ',
  'queen elizabeth': 'クイーン・エリザベス', regensburg: 'レーゲンスブルク', reno: 'リノ', repulse: 'レパルス', richelieu: 'リシュリュー',
  roon: 'ローン', 'san diego': 'サンディエゴ', saratoga: 'サラトガ', sheffield: 'シェフィールド', shimakaze: '島風', shinano: '信濃',
  shoukaku: '翔鶴', sirius: 'シリアス', 'south dakota': 'サウスダコタ', 'sovetskaya rossiya': 'ソビエツカヤ・ロシア',
  'sovetsky soyuz': 'ソビエツキー・ソユーズ', 'st. louis': 'セントルイス', taihou: '大鳳', takao: '高雄', tashkent: 'タシュケント',
  tirpitz: 'ティルピッツ', torricelli: 'トリチェリ', tosa: '土佐', trieste: 'トリエステ', 'u-47': 'U-47', 'ulrich von hutten': 'ウルリッヒ・フォン・フッテン',
  unicorn: 'ユニコーン', vampire: 'ヴァンパイア', victorious: 'ヴィクトリアス', 'vittorio veneto': 'ヴィットリオ・ヴェネト', warspite: 'ウォースパイト',
  yamashiro: '山城', yukikaze: '雪風', yuudachi: '夕立', 'z23': 'Z23', 'z46': 'Z46', zara: 'ザラ', zuikaku: '瑞鶴',
};

const POKEMON = {
  acerola: 'アセロラ', aggron: 'ボスゴドラ', arbok: 'アーボック', arcanine: 'ウインディ', archie: 'アオギリ', arven: 'ペパー',
  bea: 'サイトウ', bede: 'ビート', bianca: 'ベル', blaziken: 'バシャーモ', bonnie: 'ユリーカ', brendan: 'ユウキ', caitlin: 'カトレア',
  calem: 'カルム', candice: 'スズナ', carmine: 'ゼイユ', charmeleon: 'リザード', cheren: 'チェレン', chloe: 'コハル', courtney: 'カガリ',
  cyclizar: 'モトトカゲ', cynthia: 'シロナ', dawn: 'ヒカリ', dendra: 'ミモザ', dialga: 'ディアルガ', dragonite: 'カイリュー', elesa: 'カミツレ',
  emmet: 'ノボリ', entei: 'エンテイ', erika: 'エリカ', ethan: 'ヒビキ', falkner: 'ハヤト', feraligatr: 'オーダイル', florian: 'ハルト',
  gladion: 'グラジオ', gloria: 'ユウリ', goh: 'ゴウ', green: 'グリーン', greninja: 'ゲッコウガ', groudon: 'グラードン', grusha: 'グルーシャ',
  'hex maniac': 'オカルトマニア', hilbert: 'トウヤ', hilda: 'トウコ', 'ho-oh': 'ホウオウ', hop: 'ホップ', houndoom: 'ヘルガー',
  incineroar: 'ガオガエン', infernape: 'ゴウカザル', ingo: 'クダリ', iono: 'ナンジャモ', irida: 'カイ', iris: 'アイリス', james: 'コジロウ',
  jasmine: 'ミカン', jessie: 'ムサシ', joy: 'ジョーイ', juliana: 'アオイ', kiawe: 'カキ', kieran: 'スグリ', klara: 'クララ',
  koraidon: 'コライドン', kris: 'クリス', krookodile: 'ワルビアル', kukui: 'ククイ博士', kyogre: 'カイオーガ', lana: 'スイレン',
  leaf: 'リーフ', leon: 'ダンデ', lillie: 'リーリエ', lisia: 'ルチア', lorelei: 'カンナ', lucario: 'ルカリオ', lucas: 'コウキ', lugia: 'ルギア',
  lusamine: 'ルザミーネ', luxray: 'レントラー', lyra: 'コトネ', machamp: 'カイリキー', machoke: 'ゴーリキー', mallow: 'マオ', marnie: 'マリィ',
  maxie: 'マツブサ', may: 'ハルカ', melony: 'メロン', mew: 'ミュウ', mewtwo: 'ミュウツー', milo: 'ヤロー', miraidon: 'ミライドン',
  misty: 'カスミ', morty: 'マツバ', n: 'N', nate: 'キョウヘイ', nemona: 'ネモ', nessa: 'ルリナ', nidoking: 'ニドキング',
  obstagoon: 'タチフサグマ', oleana: 'オリーヴ', palkia: 'パルキア', pangoro: 'ゴロンダ', penny: 'ボタン', piers: 'ネズ', 'primal groudon': 'ゲンシグラードン',
  'primal kyogre': 'ゲンシカイオーガ', 'professor turo': 'フトゥー博士', raihan: 'キバナ', rayquaza: 'レックウザ', red: 'レッド', rika: 'チリ',
  rillaboom: 'ゴリランダー', rosa: 'メイ', sabrina: 'ナツメ', salamence: 'ボーマンダ', sceptile: 'ジュカイン', selene: 'ミヅキ', serena: 'セレナ',
  shauna: 'サナ', skyla: 'フウロ', snorlax: 'カビゴン', solgaleo: 'ソルガレオ', sonia: 'ソニア', swampert: 'ラグラージ',
  toxtricity: 'ストリンダー', tyranitar: 'バンギラス', tyrantrum: 'ガチゴラス', victor: 'マサル', volo: 'ウォロ', wally: 'ミツル', wicke: 'ウツギ博士',
  yellow: 'イエロー', zebstrika: 'ゼブライカ', zekrom: 'ゼクロム', zeraora: 'ゼラオラ', riolu: 'リオル', fuecoco: 'ホゲータ', quaxly: 'クワッス',
  quaxwell: 'ウェルカモ', quaquaval: 'ウェーニバル',
};

const UMAMUSUME = {
  'admire vega': 'アドマイヤベガ', 'agnes digital': 'アグネスデジタル', 'agnes tachyon': 'アグネスタキオン', 'air groove': 'エアグルーヴ',
  'air shakur': 'エアシャカール', 'akikawa yayoi': '秋川やよい', 'aston machan': 'アストンマーチャン', 'biwa hayahide': 'ビワハヤヒデ',
  'calstone light o': 'カルストンライトオ', cesario: 'シーザリオ', 'cheval grand': 'シュヴァルグラン', 'copano rickey': 'コパノリッキー',
  'curren chan': 'カレンチャン', 'daiichi ruby': 'ダイイチルビー', 'daitaku helios': 'ダイタクヘリオス', 'daiwa scarlet': 'ダイワスカーレット',
  'dantsu flame': 'ダンツフレーム', 'daring tact': 'デアリングタクト', 'dream journey': 'ドリームジャーニー', duramente: 'ドゥラメンテ', durandal: 'デュランダル',
  'eishin flash': 'エイシンフラッシュ', 'el condor pasa': 'エルコンドルパサー', 'fine motion': 'ファインモーション', 'fuji kiseki': 'フジキセキ',
  gentildonna: 'ジェンティルドンナ', 'gold city': 'ゴールドシチー', 'gold ship': 'ゴールドシップ', 'grass wonder': 'グラスワンダー', 'happy meek': 'ハッピーミーク',
  'haru urara': 'ハルウララ', 'hishi akebono': 'ヒシアケボノ', 'hishi miracle': 'ヒシミラクル', 'hokko tarumae': 'ホッコータルマエ', 'ikuno dictus': 'イクノディクタス',
  'inari one': 'イナリワン', 'ines fujin': 'アイネスフウジン', 'jungle pocket': 'ジャングルポケット', 'k.s.miracle': 'ケイエスミラクル', 'katsuragi ace': 'カツラギエース',
  'kawakami princess': 'カワカミプリンセス', "kin'iro ryotei": 'キンイロリョテイ', 'king halo': 'キングヘイロー', 'kitasan black': 'キタサンブラック',
  'manhattan cafe': 'マンハッタンカフェ', maruzensky: 'マルゼンスキー', 'marvelous sunday': 'マーベラスサンデー', 'matikane tannhauser': 'マチカネタンホイザ',
  matikanefukukitaru: 'マチカネフクキタル', 'mayano top gun': 'マヤノトップガン', 'meisho doto': 'メイショウドトウ', 'mejiro ardan': 'メジロアルダン',
  'mejiro bright': 'メジロブライト', 'mejiro dober': 'メジロドーベル', 'mejiro mcqueen': 'メジロマックイーン', 'mejiro palmer': 'メジロパーマー',
  'mejiro ramonu': 'メジロラモーヌ', 'mihono bourbon': 'ミホノブルボン', 'mr. c.b.': 'ミスターシービー', 'nakayama festa': 'ナカヤマフェスタ',
  'narita brian': 'ナリタブライアン', 'narita taishin': 'ナリタタイシン', 'narita top road': 'ナリタトップロード', 'neo universe': 'ネオユニヴァース',
  'nice nature': 'ナイスネイチャ', 'nishino flower': 'ニシノフラワー', 'oguri cap': 'オグリキャップ', 'rhein kraft': 'ラインクラフト', 'rice shower': 'ライスシャワー',
  'sakura chiyono o': 'サクラチヨノオー', 'sakura laurel': 'サクラローレル', 'satono crown': 'サトノクラウン', 'satono diamond': 'サトノダイヤモンド',
  'seiun sky': 'セイウンスカイ', 'silence suzuka': 'サイレンススズカ', 'sirius symboli': 'シリウスシンボリ', 'smart falcon': 'スマートファルコン',
  'special week': 'スペシャルウィーク', 'still in love': 'スティルインラブ', 'super creek': 'スーパークリーク', 'sweep tosho': 'スイープトウショウ',
  'symboli kris s': 'シンボリクリスエス', 'symboli rudolf': 'シンボリルドルフ', 't.m. opera o': 'テイエムオペラオー', 'taiki shuttle': 'タイキシャトル',
  'tamamo cross': 'タマモクロス', 'tanino gimlet': 'タニノギムレット', 'tokai teio': 'トウカイテイオー', 'tosen jordan': 'トーセンジョーダン',
  transcend: 'トランセンド', 'tsurumaru tsuyoshi': 'ツルマルツヨシ', 'twin turbo': 'ツインターボ', verxina: 'ヴィルシーナ', vivlos: 'ヴィブロス', vodka: 'ウオッカ',
  'win variation': 'ウインバリアシオン', 'winning ticket': 'ウイニングチケット', 'wonder acute': 'ワンダーアキュート', 'yaeno muteki': 'ヤエノムテキ',
  'yamanin zephyr': 'ヤマニンゼファー', 'yukino bijin': 'ユキノビジン',
};

const GENSHIN = {
  aether: '空', albedo: 'アルベド', alhaitham: 'アルハイゼン', amber: 'アンバー', aranara: 'アランナラ', arlecchino: 'アルレッキーノ',
  baizhu: '白朮', barbara: 'バーバラ', 'baron bunny': 'ウサギ伯爵', beidou: '北斗', 'boo tao': '胡桃', candace: 'キャンディス', changsheng: '長生',
  charlotte: 'シャルロット', chevreuse: 'シュヴルーズ', chiori: '千織', chongyun: '重雲', clorinde: 'クロリンデ', collei: 'コレイ', columbina: 'コロンビーナ',
  cyno: 'セノ', dehya: 'ディシア', diluc: 'ディルック', diona: 'ディオナ', dodoco: 'ドドコ', dottore: '博士', eula: 'エウルア', faruzan: 'ファルザン',
  fischl: 'フィッシュル', focalors: 'フォカロルス', freminet: 'フレミネ', furina: 'フリーナ', gaming: '嘉明', ganyu: '甘雨', gorou: 'ゴロー', guoba: 'グゥオパァー',
  hilichurl: 'ヒルチャール', 'hu tao': '胡桃', jean: 'ジン', kachina: 'カチーナ', kaeya: 'ガイア', kaveh: 'カーヴェ', keqing: '刻晴', kirara: '綺良々', klee: 'クレー',
  layla: 'レイラ', lisa: 'リサ', lumine: '蛍', lynette: 'リネット', lyney: 'リネ', mavuika: 'マーヴィカ', mona: 'モナ', mualani: 'ムアラニ', nahida: 'ナヒーダ',
  navia: 'ナヴィア', neuvillette: 'ヌヴィレット', nilou: 'ニィロウ', ningguang: '凝光', noelle: 'ノエル', oz: 'オズ', paimon: 'パイモン', qiqi: '七七', razor: 'レザー',
  'rex lapis': '岩王帝君', rosaria: 'ロサリア', rukkhadevata: 'マハールッカデヴァータ', sayu: '早柚', scaramouche: 'スカラマシュ', shenhe: '申鶴',
  sigewinne: 'シグウィン', signora: 'シニョーラ', sucrose: 'スクロース', tartaglia: 'タルタリヤ', thoma: 'トーマ', tighnari: 'ティナリ', venti: 'ウェンティ',
  wanderer: '放浪者', wriothesley: 'リオセスリ', xiangling: '香菱', xianyun: '閑雲', xiao: '魈', xilonen: 'シロネン', xingqiu: '行秋', xinyan: '辛炎',
  'yanfei': '煙緋', yaoyao: 'ヨォーヨ', yelan: '夜蘭', yoimiya: '宵宮', yuegui: '月桂', 'yun jin': '雲菫', zhongli: '鍾離',
};

const FIRE_EMBLEM = {
  alear: 'リュール', alfonse: 'アルフォンス', azura: 'アクア', byleth: 'ベレト', camilla: 'カミラ', catria: 'カチュア', celica: 'セリカ', celine: 'セリーヌ',
  chloe: 'クロエ', chrom: 'クロム', citrinne: 'シトリニカ', cordelia: 'ティアモ', corrin: 'カムイ', diamant: 'ディアマンド', eirika: 'エイリーク',
  elise: 'エリーゼ', eliwood: 'エリウッド', etie: 'エーティエ', fae: 'ファ', felicia: 'フェリシア', fjorm: 'フィヨルム', flayn: 'フレン', florina: 'フロリーナ',
  framme: 'フラン', goldmary: 'ゴルドマリー', grima: 'ギムレー', hinoka: 'ヒノカ', hortensia: 'オルテンシア', ike: 'アイク', ishtar: 'イシュタル', ivy: 'アイビー',
  julia: 'ユリア', kagero: 'カゲロウ', kana: 'カンナ', kiran: 'エクラ', lapis: 'ラピス', lethe: 'レテ', lilina: 'リリーナ', lissa: 'リズ', lucina: 'ルキナ',
  lyn: 'リン', marth: 'マルス', mia: 'ワユ', micaiah: 'ミカヤ', mist: 'ミスト', morgan: 'ルフレ', myrrh: 'ミルラ', ninian: 'ニニアン', nino: 'ニノ',
  nowi: 'ノノ', olivia: 'オリヴィエ', palla: 'パオラ', panette: 'パネトネ', rhea: 'レア', robin: 'ルフレ', roy: 'ロイ', ryoma: 'リョウマ', sakura: 'サクラ',
  selkie: 'キヌ', severa: 'セレナ', sharena: 'シャロン', sommie: 'Sommie', sophia: 'ソフィーヤ', soren: 'セネリオ', sothis: 'ソティス', takumi: 'タクミ',
  tana: 'ターナ', tharja: 'サーリャ', tiki: 'チキ', timerra: 'ミスティラ', veronica: 'ヴェロニカ', veyle: 'ヴェイル', yunaka: 'ユナカ', yune: 'ユンヌ',
};

const HONKAI_STAR_RAIL = {
  acheron: '黄泉', argenti: 'アルジェンティ', asta: 'アスター', aventurine: 'アベンチュリン', bailu: '白露', 'black swan': 'ブラックスワン', blade: '刃', boothill: 'ブートヒル',
  caelus: '穹', clara: 'クラーラ', 'dan heng': '丹恒', 'dr. ratio': 'Dr.レイシオ', feixiao: '飛霄', firefly: 'ホタル', 'fu xuan': '符玄', guinaifen: '桂乃芬',
  herta: 'ヘルタ', himeko: '姫子', huohuo: 'フォフォ', jade: 'ジェイド', jingliu: '鏡流', kafka: 'カフカ', lingsha: '霊砂', luocha: '羅刹', 'march 7th': '三月なのか',
  moze: 'モゼ', phainon: 'ファイノン', 'pom-pom': 'パム', qingque: '青雀', robin: 'ロビン', 'ruan mei': 'ルアン・メェイ', seele: 'ゼーレ', 'silver wolf': '銀狼', sparkle: '花火', stelle: '星',
  sunday: 'サンデー', sushang: '素裳', 'the herta': 'マダム・ヘルタ', tingyun: '停雲', topaz: 'トパーズ', trailblazer: '開拓者', yanqing: '彦卿', yunli: '雲璃',
};

const GRANBLUE = {
  andira: 'アンチラ', anila: 'アニラ', beatrix: 'ベアトリクス', cagliostro: 'カリオストロ', catura: 'カトル', charlotta: 'シャルロッテ', clarisse: 'クラリス',
  djeeta: 'ジータ', europa: 'エウロペ', ferry: 'フェリ', galleon: 'ガレヲン', gran: 'グラン', ilsa: 'イルザ', io: 'イオ', 'jeanne d\'arc': 'ジャンヌダルク',
  katalina: 'カタリナ', kumbhira: 'クビラ', lyria: 'ルリア', magisa: 'マギサ', mahira: 'マキラ', metera: 'メーテラ', narmaya: 'ナルメア', nier: 'ニーア',
  rosetta: 'ロゼッタ', sandalphon: 'サンダルフォン', sen: 'セン', silva: 'シルヴァ', societte: 'ソシエ', sturm: 'スツルム', threo: 'サラーサ', tweyen: 'ソーン',
  vajra: 'ヴァジラ', vikala: 'ビカラ', vira: 'ヴィーラ', yaia: 'ヤイア', yuel: 'ユエル', yuisis: 'ユイシス', zeta: 'ゼタ', zooey: 'ゾーイ',
};

const KEMONO_FRIENDS = {
  aardwolf: 'タテガミオオカミ', 'african wild dog': 'リカオン', 'alpaca suri': 'アルパカ・スリ', aurochs: 'オーロックス', 'black-tailed prairie dog': 'プレーリードッグ',
  'brown bear': 'ヒグマ', captain: 'キャプテン', caracal: 'カラカル', 'common dolphin': 'カマイルカ', 'common raccoon': 'アライグマ', coyote: 'コヨーテ', dhole: 'ドール',
  'dire wolf': 'ダイアウルフ', 'emperor penguin': 'コウテイペンギン', 'eurasian eagle owl': 'ワシミミズク', 'ezo red fox': 'キタキツネ', fennec: 'フェネック',
  'gentoo penguin': 'ジェンツーペンギン', 'golden snub-nosed monkey': 'キンシコウ', 'grey wolf': 'タイリクオオカミ', hippopotamus: 'カバ', 'island fox': 'アイランドフォックス',
  jaguar: 'ジャガー', 'japanese crested ibis': 'トキ', kaban: 'かばん', lion: 'ライオン', 'lucky beast': 'ラッキービースト', moose: 'ヘラジカ',
  'northern white-faced owl': 'アフリカオオコノハズク', 'scarlet ibis': 'ショウジョウトキ', serval: 'サーバル', shoebill: 'ハシビロコウ', 'siberian chipmunk': 'シマリス',
  'silver fox': 'ギンギツネ', 'small-clawed otter': 'コツメカワウソ', 'southern tamandua': 'オオアリクイ', 'superb bird-of-paradise': 'カンザシフウチョウ', 'white lion': 'ホワイトライオン',
  'white rhinoceros': 'シロサイ', 'wild tiger': 'トラ', yak: 'ヤク',
};

const LEAGUE_OF_LEGENDS = {
  annie: 'アニー', ashe: 'アッシュ', 'aurelion sol': 'オレリオン・ソル', garen: 'ガレン', gwen: 'グウェン', janna: 'ジャンナ', jinx: 'ジンクス', katarina: 'カタリナ',
  leblanc: 'ルブラン', leona: 'レオナ', lulu: 'ルル', lux: 'ラックス', 'miss fortune': 'ミス・フォーチュン', mordekaiser: 'モルデカイザー', nasus: 'ナサス',
  neeko: 'ニーコ', rengar: 'レンガー', riven: 'リヴェン', seraphine: 'セラフィーン', sett: 'セト', sona: 'ソナ', soraka: 'ソラカ', thresh: 'スレッシュ',
  volibear: 'ボリベア', wolf: 'ウルフ', yasuo: 'ヤスオ', zac: 'ザック',
};

const GROUP_NAMES = {
  kancolle: KANCOLLE,
  fate: FATE,
  'blue archive': BLUE_ARCHIVE,
  arknights: ARKNIGHTS,
  'azur lane': AZUR_LANE,
  pokemon: POKEMON,
  umamusume: UMAMUSUME,
  'genshin impact': GENSHIN,
  'fire emblem': FIRE_EMBLEM,
  'honkai star rail': HONKAI_STAR_RAIL,
  'granblue fantasy': GRANBLUE,
  'kemono friends': KEMONO_FRIENDS,
  'league of legends': LEAGUE_OF_LEGENDS,
};

const QUALIFIERS = new Map([
  ['kai ni', '改二'], ['kai san', '改三'], ['retrofit', '改造'], ['swimsuit', '水着'], ['school uniform', '制服'],
  ['black dress', '黒ドレス'], ['red dress', '赤いドレス'], ['white dress', '白いドレス'], ['summer', '夏衣装'], ['casual', '私服'],
  ['1st costume', '初期衣装'], ['2nd costume', '第2衣装'], ['3rd costume', '第3衣装'], ['first ascension', '第1再臨'],
  ['second ascension', '第2再臨'], ['third ascension', '第3再臨'], ['female', '女性'], ['male', '男性'], ['adult', '大人'],
  ['young', '幼少期'], ['small', '幼少期'], ['maid', 'メイド衣装'], ['track', 'トラック衣装'], ['nurse', 'ナース衣装'],
  ['work', '仕事着'], ['gothic lolita', 'ゴシックロリータ'], ['button-down', 'ボタンダウン'], ['loungewear', 'ルームウェア'],
  ['street', 'ストリート衣装'], ['on campus', '学園内'], ['red dress', '赤いドレス'], ['black dress', '黒いドレス'],
  ['the radiant knight', '耀騎士'], ['the corrupting heart', '腐蝕せし心'], ['the unchained', '解放された姿'], ['the holungday', 'ホルンデイ'],
  ['swimsuit mooncancer', '水着ムーンキャンサー'], ['swimsuit berserker', '水着バーサーカー'],
  ['the herta', 'マダム・ヘルタ'], ['run revolt launcher', 'ラン・レヴォルト・ランチャー'], ['lunatic lab', 'ルナティック・ラボ'],
  ['rain witch', '雨の魔女'], ['emerald float', 'エメラルド・フロート'], ['festival outfit', '祭装'], ['traveling outfit', '旅装'],
  ['amour caren', 'アムール・カレン'], ['amor caren', 'アムール・カレン'], ['foreign swimsuit', '水着'], ['swimsuit foreigner', '水着フォーリナー'],
]);

function splitTag(tag) {
  const source = String(tag);
  const firstParenthesis = source.indexOf('(');
  const base = firstParenthesis < 0 ? source : source.slice(0, firstParenthesis);
  const parts = [...source.matchAll(/\(([^()]*)\)/g)]
    .map(match => match[1].trim())
    .filter(Boolean);
  return { base: normalize(base), parts };
}

function qualifier(value) {
  const key = normalize(value);
  if (QUALIFIERS.has(key)) return QUALIFIERS.get(key);
  const swimsuitRole = key.match(/^swimsuit (archer|rider|ruler|saber|lancer|assassin|pretender|foreigner|berserker)$/);
  if (swimsuitRole) return `水着${swimsuitRole[1].replace(/^./, char => char.toUpperCase())}`;
  const ascension = key.match(/^(first|second|third) ascension$/);
  if (ascension) return `${{ first: '第1', second: '第2', third: '第3' }[ascension[1]]}再臨`;
  const costume = key.match(/^(first|second|third) costume$/);
  if (costume) return `${{ first: '第1', second: '第2', third: '第3' }[costume[1]]}衣装`;
  const title = String(value).replace(/\s+/g, ' ').trim();
  return title ? title.replace(/\b\w/g, char => char.toUpperCase()) : '';
}

function titleFor(work) {
  return WORK_NAMES[normalize(work)] ?? null;
}

function restoreWorkTitle(name, tag) {
  if (typeof name !== 'string') return name;
  const sourceParts = [...String(tag).matchAll(/\(([^()]*)\)/g)].map(match => match[1].trim());
  const work = sourceParts.at(-1);
  const title = titleFor(work);
  if (!title) return name;
  const trailing = name.match(/(?:（([^（）]*)）|\(([^()]*)\))$/);
  const trailingWork = trailing?.[1] ?? trailing?.[2];
  const sameWork = trailingWork && [work, title]
    .map(value => normalize(value))
    .includes(normalize(trailingWork));
  const withoutWork = sameWork
    ? name.slice(0, trailing.index)
    : name;
  return `${withoutWork}（${title}）`;
}

function looksMachineTranslated(value) {
  return /賞賛する|大人の海王星|一承認されています|一般的な|青いアーカイブ|航空機キャリア|最初のアセンション|第二性性能|フィニッシュラインフラッグベアラー|第2の昇天|メガマンzx/i.test(value);
}

function prettyFallback(base) {
  return String(base)
    .replace(/[_-]+/g, match => match.includes('-') ? '-' : ' ')
    .replace(/\b\w/g, char => char.toUpperCase())
    .replace(/\s+/g, ' ')
    .trim();
}

function reviewTag(tag, previous) {
  let { base, parts } = splitTag(tag);
  const inlineVariant = base.match(/^(.*)\s+(kai ni|kai san)$/);
  if (inlineVariant) {
    base = normalize(inlineVariant[1]);
    parts = [inlineVariant[2], ...parts];
  }
  const work = parts.length && titleFor(parts.at(-1)) ? normalize(parts.at(-1)) : null;
  const variants = work ? parts.slice(0, -1) : parts;
  const group = work ? GROUP_NAMES[work] : null;
  const directMapped = GLOBAL_NAMES[normalize(tag)];
  if (directMapped) {
    return directMapped;
  }
  const mapped = group?.[base] ?? GLOBAL_NAMES[base] ?? directMapped;

  if (!mapped && previous && !looksMachineTranslated(previous)) {
    return restoreWorkTitle(previous, tag);
  }

  const name = mapped ?? prettyFallback(base);
  const variantText = variants.map(qualifier).filter(Boolean).map(value => `（${value}）`).join('');
  return `${name}${variantText}${work ? `（${WORK_NAMES[work]}）` : ''}`;
}

const sourceTags = fs.readFileSync(sourcePath, 'utf8')
  .split(/\r?\n/)
  .slice(1)
  .filter(Boolean)
  .map(line => line.split(',')[1]?.trim())
  .filter(Boolean);
const database = JSON.parse(fs.readFileSync(characterPath, 'utf8'));
const japanese = { ...(database['ja-JP'] ?? {}) };

const allTags = new Set([...sourceTags, ...Object.keys(japanese)]);
for (const tag of allTags) {
  japanese[tag] = reviewTag(tag, japanese[tag]);
}

for (const [tag, name] of Object.entries(japanese)) {
  japanese[tag] = restoreWorkTitle(name, tag);
}

database['ja-JP'] = Object.fromEntries(
  Object.entries(japanese).sort(([left], [right]) => left.localeCompare(right)),
);
fs.writeFileSync(characterPath, `${JSON.stringify(database, null, 2)}\n`, 'utf8');

const officialWorkNames = JSON.parse(fs.readFileSync(officialWorkPath, 'utf8'));
for (const [work, title] of Object.entries(WORK_NAMES)) {
  officialWorkNames[work] = title;
}
fs.writeFileSync(officialWorkPath, `${JSON.stringify(officialWorkNames, null, 2)}\n`, 'utf8');

console.log(JSON.stringify({
  sourceTags: sourceTags.length,
  japaneseEntries: Object.keys(database['ja-JP']).length,
  covered: sourceTags.filter(tag => database['ja-JP'][tag]).length,
}, null, 2));
